### PR TITLE
fix(gnovm): don't print to stdout by default

### LINKED ISSUE #3075: println DoS
### Description

A smart contract on test4 is printing out a debug message, effectively bringing down nodes.

https://github.com/gnoswap-labs/gnoswap/blob/28738c182561b11db7c338e150a4d7108b3c94a4/_deploy/r/gnoswap/gns/gns.gno#L120-L123

### Your environment

Test4

### Logs

gnoland-1  |   > REWARD__EXTERNAL_max: 1723091158
gnoland-1  |   > REWARD__EXTERNAL_time.Now().Unix(): 1730903575
gnoland-1  |   > REWARD__EXTERNAL_consts.BLOCK_GENERATION_INTERVAL: 2
gnoland-1  |   > REWARD__EXTERNAL_stakedOrExternalDuration: 3906208
gnoland-1  |   > REWARD__EXTERNAL_height: 3263060
gnoland-1  |   > REWARD__EXTERNAL_stakedOrExternalStartedHeight: -643148
gnoland-1  |    > REWARD__EXTERNAL_incentiveId: ZzFsbXZycnJyNGVyMnVzODRoMjczMnNydTc2Yzl6bDJudmtuaGE4Yzpnbm8ubGFuZC9yL2RlbW8vd3Vnbm90Omduby5sYW5kL3IvZ25vc3dhcC92Mi9nbnM6MzAwMDpnbm8ubGFuZC9yL2RlbW8vd3Vnbm90OjE3MjMwNzUyMDA6MTczMDg1MTIwMDo3MTg1NTA=
gnoland-1  |    > REWARD__EXTERNAL_tokenAmountX96: 2865800446646703484598463409694289977
gnoland-1  |    > REWARD__EXTERNAL_positionLastExternal[tokenId][incentiveId]: 2838829677538662475374750163641100678
gnoland-1  |    > REWARD__EXTERNAL_toDistributeX96: 26970769108041009223713246053189299
gnoland-1  |    > REWARD__EXTERNAL_lastCalculatedHeightU64: 934385
gnoland-1  |    > REWARD__EXTERNAL_toDistirbuteX96: 26970769108041009223713246053189299
gnoland-1  |    > REWARD__EXTERNAL_uint64(std.GetHeight())-lastCalculatedHeightU64): 2328675
gnoland-1  |    > REWARD__EXTERNAL_avgExternalBlockAmountX96: 11582023729391610775961972389
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.full100 0
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.give100 0
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.left100 0
gnoland-1  | 
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.full70 19318301
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.give70 13522807
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.left70 5795494
gnoland-1  | 
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.full50 6583630
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.give50 3291810
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.left50 3291820
gnoland-1  | 
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.full30 10269532
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.give30 3080856
gnoland-1  |    > REWARD__EXTERNAL_BEFORE_positionExternalWarmUpAmount.left30 7188676
gnoland-1  | 
gnoland-1  |  > REWARD__EXTERNAL_REWARD ONLY 100%
gnoland-1  |   > REWARD__EXTERNAL_DUR100 2328675
gnoland-1  | 

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

### PR DESCRIPTION
**Pull request by thehowl**
Attempt to fix #3075 

cc/ @zivkovicmilos @sw360cab

### CODE REVIEW

**Comment by moul** [comment]
By default or with a flag?

**Comment by thehowl** [comment]
>By default or with a flag?

By default. I think this shouldn't be configurable on the gnoland node per se?

>@gfanton what about gnodev?

This was also a concern of mine, but I was eager to get a fix out asap as from what I understood this was a show-stopper bug, but seems like it wasn't too much after all.

I went back and added an option so that gnodev can set os.Stdout as the output.

**Review by moul — APPROVED** [review]

**Comment by moul** [comment]
> By default. I think this shouldn't be configurable on the gnoland node per se?

I agree.

**Review by gfanton — APPROVED** [review]
You can keep `gnodev` this way for now; it's partially fine. Just remember that `gnodev` operates in raw term mode, which means newlines should be written as `\r\n`. As a result, outputting directly to stdout will not display as expected. These logs are infrequent on `gnodev` during local development, so it's manageable, but it remains a temporary solution.  

This issue is part of a larger problem: `gnodev` currently cannot display node logs. We need to implement a proper method for displaying both node logs and this type of output without affecting the readability of `gnodev` logs. It's important to note that node logs are rarely needed for a lambda user, as they tend to be excessively verbose.

**Pull request merged**
