### PR TITLE
fix: check nil where reading bytes from ArrayValue.List

### PR DESCRIPTION
**Pull request by ltzmaxwell**

### CODE REVIEW

**Review by moul — APPROVED** [review]

**Review by moul — COMMENTED** [review]
Hum, sorry, thinking more.

Maybe we should stop at first encountered nil.

Can you provide the test/thing that made you notice this?

**Comment by ltzmaxwell** [comment]
I built a marshal function, use the returned value an input to call std.Hash(), then an nil pointer exeption happened.
The marshal function is like this:

```
pn.DefineNative("Marshal",
	gno.Flds( // params
		"bz", gno.InterfaceT(nil),
	),
	gno.Flds( // results
		"js", "[]byte",
	),
	func(m *gno.Machine) {
		arg0 := m.LastBlock().GetParams1().TV
		in := arg0.V.(interface{})
		js, _ := json.Marshal(in)
		res0 := gno.Go2GnoValue(
			m.Alloc,
			m.Store,
			reflect.ValueOf(js),
		)
		m.PushValue(res0)
	},
)

```
The reason is that when we were calling the 'Go2GnoValue', it initialized a SliceValue calling https://github.com/gnolang/gno/blob/f0bd8b5754b48a248fdcc0e6ede51d142f3410e4/pkgs/gnolang/alloc.go#L223-L235   , which built an underlying ArrayValue with  the given list, and when we were reading bytes from it: https://github.com/gnolang/gno/blob/f0bd8b5754b48a248fdcc0e6ede51d142f3410e4/pkgs/gnolang/values.go#L312-L329
an exception will happen because of the nil item.


change some lines here, 


```
pn.DefineNative("Marshal",
    gno.Flds( // params
		"bz", gno.InterfaceT(nil),
	),
	gno.Flds( // results
	    "js", "[]byte",
	    "ok", "bool",
	),
	func(m *gno.Machine) {
		arg0 := m.LastBlock().GetParams1().TV
		in := arg0.V.(interface{})
		js, err := json.Marshal(in)
		if err != nil {
            m.PushValue(typedByteSlice(m.Alloc.NewSliceFromData(js)))
			m.PushValue(typedBool(false))
		} else {
			m.PushValue(typedByteSlice(m.Alloc.NewSliceFromData(js)))
			m.PushValue(typedBool(true))
		}
	},
)

```

build the SliceValue calling https://github.com/gnolang/gno/blob/f0bd8b5754b48a248fdcc0e6ede51d142f3410e4/pkgs/gnolang/alloc.go#L238-L250
, then things going well.

**Comment by ltzmaxwell** [comment]
here is the test:

```
package main

import "std"
import "fmt"

type Target struct {
	Description string
	Name string
}

func main(){
	t := &Target{
		Description: "test",
		Name: "kimi",
	}
	r, ok := std.Marshal1(t)
	if ok{
		fmt.Printf("%s \n", r)
		println(len(r))
	}else{
		println("error")
	}
	h := std.Hash(r)
}
// Output:
// {"TV":{"T":{"PkgPath":"main","Name":"Target","Base":{"PkgPath":"main","Fields":[{"Name":"Description","Type":16,"Embedded":false,"Tag":""},{"Name":"Name","Type":16,"Embedded":false,"Tag":""}]},"Methods":null},"V":{"ID":{"PkgID":{"Hashlet":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"NewTime":0},"Hash":{"Hashlet":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"OwnerID":{"PkgID":{"Hashlet":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"NewTime":0},"ModTime":0,"RefCount":0,"Fields":[{"T":16,"V":"test","N":[0,0,0,0,0,0,0,0]},{"T":16,"V":"kimi","N":[0,0,0,0,0,0,0,0]}]},"N":[0,0,0,0,0,0,0,0]},"Base":null,"Index":0}
// 608


```

```
package main

import "std"
import "fmt"

type Target struct {
	Description string
	Name string
}

func main(){
	t := &Target{
		Description: "test",
		Name: "kimi",
	}
	r := std.Marshal2(t)
	fmt.Printf("%s \n", r)
	println(len(r))
	h := std.Hash(r)
}
// Error:
// runtime error: invalid memory address or nil pointer dereference

```

**Comment by ltzmaxwell** [comment]
https://github.com/ltzmaxwell/gno/tree/demo_test/examples/gno.land/r/demo/encoding

**Comment by piux2** [comment]
Hi @ltzmaxwell,

Can you provide your error trace?

the following method 
(av *ArrayValue) GetReadonlyBytes() []byte {

is only called from 

 https://github.com/gnolang/gno/blob/76f079df092ea0e3d1c43ed35d6ec9bdb7b34ce8/stdlibs/stdlibs.go#L157

AND

https://github.com/gnolang/gno/blob/76f079df092ea0e3d1c43ed35d6ec9bdb7b34ce8/stdlibs/stdlibs.go#L395


Question: 
How did you trace from Go2GnoValue to GetReadonlyBytes()?
Why is the fix in [GetReadonlyBytes() ](https://github.com/gnolang/gno/pull/394/files) related to the Native Marshal method created here?


(av *ArrayValue) GetReadonlyBytes() []byte  is only call when we call std.Hash() or std.EncodeBech32() from smart contract.

Possible cause:

https://github.com/ltzmaxwell/gno/tree/demo_test/examples/gno.land/r/demo/encoding

h := std.Hash(r) throws a non-pointer exception, not the Marshal function. 

Because the JSON returned from std.Marshal with Base=null. 

When smart contract call std.Hash(r)

https://github.com/ltzmaxwell/gno/blob/66465a07266acb4837fe83e6c6bbf618e8875c3e/stdlibs/stdlibs.go#L197

     array := slice.GetBase(m.Store)
    bz = array.GetReadonlyBytes()

   slice.GetBase(m.Store) return nil 
   array.GetreadonlyBytes()  through non-pointer because the array is nil. 

@moul @ltzmaxwell What do you think?

**Comment by ltzmaxwell** [comment]
I think the lengthy elaboration brings confusion, forget it. to be short, when a slice is allocated, it's assigned with the input list, so the underlying `List` field has a length of cap(list), which means there will be (cap-len)nils ,

https://github.com/gnolang/gno/blob/f0bd8b5754b48a248fdcc0e6ede51d142f3410e4/pkgs/gnolang/alloc.go#L223-L235

So it need to be checked when reading to avoid panic, like this:

for i, tv := range av.List {
 			// av.List may contain nil since it's allocated with the cap of a slice
 			if tv.T == nil {
 				break
 			}
 			
 Or, another way, we should simply change the code:
 
 https://github.com/gnolang/gno/blob/f0bd8b5754b48a248fdcc0e6ede51d142f3410e4/pkgs/gnolang/alloc.go#L226
 
 
 to  fullList := list[:len(list)].

**Comment by piux2** [comment]
@moul @ltzmaxwell 

This is correct behavior, not a bug.

For whatever reason, if tv.T is nil, it means the element type is nil interface. It should panic and throw a non-pointer by VM.

Marshal native function defined a nil interface type as a parameter.  It is expected behavior to throw a non-pointer and panic.

    pn.DefineNative("Marshal",
	    gno.Flds( // params
	>>>>>   "bz", gno.InterfaceT(nil), <<<<<<
	    ),

**Comment by ajnavarro** [comment]
@piux2 @ltzmaxwell What is the needed work missing here? should we move this forward? Thanks!

**Comment by zivkovicmilos** [comment]
@piux2 @ltzmaxwell 
Ping on this

> @piux2 @ltzmaxwell What is the needed work missing here? should we move this forward? Thanks!

**Comment by ltzmaxwell** [comment]
> @piux2 @ltzmaxwell Ping on this
> 
> > @piux2 @ltzmaxwell What is the needed work missing here? should we move this forward? Thanks!

I'll review whether to renew the first request or close it.

**Comment by ltzmaxwell** [comment]
close it, might be invalid assumption. no other issues found causes by this.

**Pull request closed without merging**
