### PR TITLE
feat(stdlibs): simplify time pkg & remove tz + monoclock logic related

### LINKED ISSUE #851: rfc: change the `time` stdlib package
Following Jae's comments on #657:

> I _think_ this might be the right thing to do, but it's a bit weird.
> 
> One, we need to make sure that the declaration of type Location is safe, for when Location is ever set (now or in the future). So for example, Location shouldn't be modifiable, otherwise any user can modify a *Location for all users, a bad security breach. Not only should we scan the stdlibs/time code, but also I guess everything about the current implementation, including functions that haven't been ported yet, to make sure it will always be safe to completely port it and maintain it.
> 
> Also, it seems a bit unnecessary to support this time implementation because (a) it is a struct, which is more expensive than a primary value, (b) at least in the blockchain context we don't need to support that weird "wall timer" thing, (c) it honestly seems way too complex even in Go because of the "wall timer" thing. So I imagine we may want to implement another "time" package for gno in the future that is simpler.
> 
> But anyways, the stdlibs/time.Format is already used for boards, so seems fine to go ahead for now.

My thoughts: I do think that a `time` package should be as close as possible to Go's, because `time`'s methods and types are probably the ones I've committed to memory the most. But I agree it can probably be simplified, especially re: Location and monotonic time, both of which have relative importance in the blockchain chase.

We could make it so the `time` package always works in UTC by default, with no concept of a "local" time, but retaining the Location struct; so we can then add methods like `FormatInLocation` which can display time to the user in their local times. We could then add a `tzdata` package (not in stdlib) that stores the tzdata for all locations (so that a package/realm can do `tzdata.Get("Europe/Rome")`, returning a `*Location` which does not affect other users.

One more thought re: usability. From the end user side, reading times only in UTC on a real-life realm, say the new #791 microblog realm, I think can be very annoying if they're not of the crowd of remote workers who are used to converting back and forth their local time to UTC anyway. So continuing on #439, I think we could think about a way to custom-render time in markdown; for instance:

```
Posted on [11 Jan 2020 11:10 UTC](#time-RFC822)

Posted on [11/01/2020](#time-02%2F01%2F2006)
```

This is understood by "smart renderers" which can adjust this to be in the viewer's timezone (client-side), by parsing the time with the given format assuming a UTC location if not given, using Go's reference time (`01/02 03:04:05PM '06 -0700`) and understanding common time formats which are constants in the time package.

### PR DESCRIPTION
**Pull request by MikaelVallenet**
fix #851

The purpose of this Pull Request is to simplify the Time pkg, which comes from Go, in order to remove unnecessary functions for Gno. 

This Pull Request removes the concept of monotonic clock, which corresponds to the time since the start of the program, often used to calculate the time interval between two events more reliably.

I've also removed the notion of timezone, and now an instance of Time is composed as follows:

```go
type Time struct {
	sec  int64
	nsec int32
}
```

When I parse a date with a different timezone, it's automatically transformed into UTC.
However, the goal would be to allow a Time instance to be displayed in a specific timezone with a markdown pattern, especially for Gnoweb.

```md
[2024-10-11 12:33:41](#local)
[2024-10-11 12:33:41](#Europe/Rome) => 2024-10-11 14:33:41 (Summer time)
```

Most of the PR is code deletion, not addition, especially the bitwise logic. [see article](https://articles.singee.me/golang-time?locale=en)

I've also adapted some unnecessary methods to avoid breaking realms, such as the Zone method, which returns the tz name and offset before the realm name, and is used in the ``events`` realm.

```go
// This method is here to avoid breaking changes but always return UTC and offset 0
func (t Time) Zone() (name string, offset int) {
	name, offset = "UTC", 0
	return
}
``` 

I also kept some unused param like Location in Date to validate the CI & keep same API as Go:

```go
func Date(year int, month Month, day, hour, min, sec, nsec int, loc *Location) Time {...}
```

In the code snippet above, i kept the `loc` parameter even if i don't use it anymore.

I'd like to take this opportunity to say that I haven't answered the testing question, because the PR seems tedious enough to review as it is. If this PR ends up being merged, I'm thinking of doing a second PR for the testing part, to keep things as atomic as possible.

> For what concerns testing, I think it's reasonable at the start of gno test to set a TimestampSeconds at the UNIX timestamp of starting the test. Or maybe we want it fixed in time... but, seeing as this is the testing environment, if we end up wanting to change it we can just change it later.
You may want to move internal/os.Sleep to the testing stdlib's time. Or maybe, let's have a SetNow which can take a time.Time to be set as the current value of Now().
_Originally posted by @thehowl in https://github.com/gnolang/gno/issues/851#issuecomment-2429753760_

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
</details>

### CODE REVIEW

**Comment by MikaelVallenet** [comment]
I will adapt the test to avoid remove it: [examples/gno.land/r/demo/boards/z_4_filetest.gno](https://github.com/gnolang/gno/pull/3016/files#diff-776b5682fe916e3bb9be4c9fbed9148523cfaefa7396df205d7360755662285c)
I will do this ASAP

**Review by moul — COMMENTED** [review]
It looks good globally. However, after discussing with Jae which parameters should be specified in the new x/params module (#3003), we believe it would be beneficial to include a "global chain default timezone" to accommodate more regional chains. We can apply the same logic of markdown-based conversion. Instead of having no timezone support or encouraging per-contract timezone support, we ideally want to implement per-chain timezone support.

**Comment by MikaelVallenet** [comment]
I understand and agree with you, i will look to adapt the PR to set the default tz as a parameter of the chain handle by x/params

**Comment by jefft0** [comment]
Hello @MikaelVallenet . Are you still updating this PR based on the comments of moul? If yes, then do you want to set this PR to draft while you are still working on it?

**Pull request closed without merging**
