### PR TITLE
chore(gnolang): add challenge for unused var

### PR DESCRIPTION
**Pull request by tbruyelle**
Can be tricky to implement because it requires a global registry that would be updated each time a variable is used.

### CODE REVIEW

**Comment by ajnavarro** [comment]
It might be possible to implement analyzing the AST directly, pinging @peter7891 for more insight.

**Comment by moul** [comment]
Maybe we can improve the `gno precompile + gno build` integration?

**Comment by tbruyelle** [comment]
> Maybe we can improve the `gno precompile + gno build` integration?

I don't understand how this is related.

**Review by thehowl — APPROVED** [review]

**Comment by moul** [comment]
> I don't understand how this is related.

The `gno precompile + gno build` command uses the standard Go compiler, which generates a warning for unused variables.

By streamlining it within the `gnodev` commands, we can take advantage of its features earlier.

**Review by moul — APPROVED** [review]

**Pull request merged**
