### PR TITLE
Website: render usernames

### PR DESCRIPTION
**Pull request by loicttn**
Simple pr to replace all  `@username` per `[@username](/r/users:username)` dynamically on website

### CODE REVIEW

**Comment by moul** [comment]
@jaekwon what do you think about this one?

I personally like it.

If if it too problematic, we can imagine writing an helper that replaces automatically the `@username` of a markdown blob. This way, a smart contract can decide to use it whe{n,r}ever it wants; i.e., on `r/boards.Post.Body`

**Comment by jaekwon** [comment]
I like doing this on the client side, but shouldn't it happen *after* markdown is all parsed?
Otherwise, there will be strange bugs, like what if the @username was part of a link text, like 
[this reference to @username](https://someotherlink). It will likely be difficult to get right w/ regexp.
But if we just do it after regexp is complete, then that's tricky too, given the way HTML works with text spans.

**Comment by jaekwon** [comment]
How about [[@username]]?

**Comment by moul** [comment]
> How about [[@username]]?

I think we should be human-friendly, and on GitHub and a lot of other platforms, this is just @username

**Comment by jaekwon** [comment]
ok. let's run with it and we can fix this later. i will make an issue.yy

**Pull request merged**
