### PR TITLE
feat: refactoring build of docker images

### PR DESCRIPTION
**Pull request by albttx**
This is a following of :

- #2062 

I am a big fan of goreleaser, but it seems that building docker images with it isn't a really good idea at the moment...

Currently, it seems to not have a latest build, only a nighly, which break portal-loop / staging ...

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Comment by albttx** [comment]
Cached is working, build time highly reduced

image

**Comment by albttx** [comment]
i need to test the images, it should works, not 100% sure

**Comment by albttx** [comment]
All good for review :) @gfanton @ajnavarro

**Comment by thehowl** [comment]
agreed w/ albert to close

**Pull request closed without merging**
