### PR TITLE
feat: add pyroscope and updates compose

### PR DESCRIPTION
**Pull request by Leon-Africa**
<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

````
FIX:
Set container names

Set network name

Add Grafana pyroscope

Instead of pulling ghcr.io image - Setup a local docker to build allowing that local low level changes made can be tested immediately. 

Add option to build with no-cache [make up fresh]

remove obsolete "version" in docker compose

Enable anonymous auth admin login so no need to enter password
````

### CODE REVIEW

**Comment by thehowl** [comment]
cc @sw360cab 

Not sure if this is something we want

**Comment by Leon-Africa** [comment]
@thehowl To elabortate this makes local testing more feasible - the existing automation pulls from [ghcr.io/gnolang/gno/gnoland](https://github.com/gnolang/gno/blob/0a662c4c673dfdcb0500ff75900b00f1e9c009b6/misc/telemetry/gnoland/Dockerfile#L) which means its static. If you make a change to a ```.go``` file you will not have any immediate feedback on how that change/s affect the node.

By using the approach of a local build developers will be able to get immediate feedback on how their changes affect the node. 

pyroscope is an additional add to that.

**Comment by sw360cab** [comment]
This PR works on two different topics
* It does solve some small defects (e.g. Dockerfiles and compose clenaups) which can be cool and apporved
* It introduces out of nowhere Grafana Peryscope within the Gno codebase. I don't see the reason to create a tight dependency like that in the Gno codebase, moreover this is actually a tool we are neither using nor planning to use.

I will close this and be happy to review code that works on the previous aspects in separeted PRs.

**Comment by Leon-Africa** [comment]
@sw360cab thanks for the feedback - will create separate pr as suggested and reference this one.

**Pull request closed without merging**
