### PR TITLE
chore(tests): don't panic on diff output

### PR DESCRIPTION
**Pull request by albttx**
# Description

We don't need panic here, diff output is much more clear like that

### CODE REVIEW

**Review by moul — APPROVED** [review]

**Review by thehowl — CHANGES_REQUESTED** [review]
I don't necessarily think of this as an improvement for the following reason:

1. It prints the error without panicking only for the given situation (e.g. Output differs) - although all other branches still fail with the panic error and in an unfriendly way.
2. There is a difference between panicking and `os.Exit(1)`, and that is on whether the other goroutines execute (assuming the panicking one is appropriately recovered). This means that when panicking, for instance executing `make test.gno`, the other file tests are still executing[^1], while if we os.Exit, the program finishes execution and no other tests run[^2].

I think a better approach would be that of rewriting this function to return errors instead of panicking, if we want a quick solution. I think this one can be done in this PR. However there is a further improvement I think we could do to the gnodev test command - I've written it up on #665 as I think it goes a bit beyond the scope of this PR.

[^1]: image

[^2]: image

**Comment by thehowl** [comment]
Any thoughts on this @albttx ?

**Comment by albttx** [comment]
Hello,

The code has been updated to:

```go
						if resWanted == "" {
							panic(fmt.Sprintf("fail on %s: got unexpected output: %s", path, res))
						} else {
							diff, _ := difflib.GetUnifiedDiffString(difflib.UnifiedDiff{
								A:        difflib.SplitLines(resWanted),
								B:        difflib.SplitLines(res),
								FromFile: "Expected",
								FromDate: "",
								ToFile:   "Actual",
								ToDate:   "",
								Context:  1,
							})
							panic(fmt.Sprintf("fail on %s: diff:\n%s\n", path, diff))
						}

```

which is better, but i agree with you, returning an error and have a cleaning "stop" would be a better solution

**Comment by thehowl** [comment]
@albttx did you forget to push?

**Pull request closed without merging**
