### PR TITLE
feat: encoding/binary (for encoding/base64)

### PR DESCRIPTION
**Pull request by r3v4s**
# Description

contract with `import encoding/base64` is failing when `gnokey maketx addpkg`
'base64' imports `binary` but there is non in `stdlibs/*`

# Additional
@thehowl I think this is related to my previous issue #808 and yours #814

### CODE REVIEW

**Comment by thehowl** [comment]
If you're adding bigEndian I think you should also add littleEndian?

Do you have an application where you need these specifically?

**Comment by schollz** [comment]
> Do you have an application where you need these specifically? 

These functions are nice-to-have so that Gno smart contracts could support encoding/decoding of various file formats. For example, I wanted both of these for a `.wav` file format encoder (https://github.com/schollz/gno/blob/bytebeat/examples/gno.land/p/demo/audio/riff/riff.gno) for developing web3 audio applications (like audio nfts).

**Comment by jaekwon** [comment]
Let's please add little endian too. 
If any stdlib functions are modified, please note the changes with XXX as well.
Thank you!

**Review by jaekwon — APPROVED** [review]
pre-approving but please add little endian too.

**Comment by r3v4s** [comment]
> Let's please add little endian too. If any stdlib functions are modified, please note the changes with XXX as well. Thank you!

thanks to your review.
I've add little endian too with test cases

**Comment by moul** [comment]
And update this file please: https://github.com/gnolang/gno/blob/master/gnovm/docs/go-gno-compatibility.md#stdlibs

**Comment by r3v4s** [comment]
> Referenc

Should I change in this PR? or create new one??

**Comment by r3v4s** [comment]
> Should I change in this PR? or create new one??



> And update this file please: https://github.com/gnolang/gno/blob/master/gnovm/docs/go-gno-compatibility.md#stdlibs

Should I change in this PR? or create new one??

**Comment by moul** [comment]
In the same please, it's to take the habit of doing it. Thank you.

**Review by thehowl — APPROVED** [review]

**Review by moul — APPROVED** [review]

**Comment by moul** [comment]
Please, run `make fmt` to fix the last small details.

```diff
diff --git a/gnovm/stdlibs/encoding/binary/binary.gno b/gnovm/stdlibs/encoding/binary/binary.gno
index 7e99d14e..08f7b3f2 100644
--- a/gnovm/stdlibs/encoding/binary/binary.gno
+++ b/gnovm/stdlibs/encoding/binary/binary.gno
@@ -200,4 +200,4 @@ func (bigEndian) AppendUint64(b []byte, v uint64) []byte {
 
 func (bigEndian) String() string { return "BigEndian" }
 
-func (bigEndian) GoString() string { return "binary.BigEndian" }
\ No newline at end of file
+func (bigEndian) GoString() string { return "binary.BigEndian" }
diff --git a/gnovm/stdlibs/encoding/binary/binary_test.gno b/gnovm/stdlibs/encoding/binary/binary_test.gno
index 05b6c369..5407eb50 100644
--- a/gnovm/stdlibs/encoding/binary/binary_test.gno
+++ b/gnovm/stdlibs/encoding/binary/binary_test.gno
@@ -3,7 +3,6 @@ package binary
 import (
    "bytes"
    "encoding/binary"
-
    "testing"
 )
 
@@ -187,4 +186,4 @@ func TestbigEndianAppendUint64(t *testing.T) {
    if !bytes.Equal(b, []byte{0xfe, 0x14, 0xf5, 0xe9, 0x07, 0xd0, 0x03, 0xe8, 0x0b, 0xb8, 0x07, 0xd0, 0xd0, 0x07, 0xe9, 0xf5}) {
        t.Fatal("bigEndian.AppendUint64 failed")
    }
-}
\ No newline at end of file
+}
```

**Review by moul — APPROVED** [review]

**Pull request merged**
