### PR TITLE
feat(coverage): Add back coverage support for `txtar`

### PR DESCRIPTION
**Pull request by gfanton**
Add back coverage support for `txtar`, which was removed during the CI rework.
This only includes `txtar` test files from `gnovm` package (not those for gnoland, I will do that in another PR).
It adds approximately **5%** coverage, which is a non-negligible.

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Review by deelawn — APPROVED** [review]

**Review by ajnavarro — CHANGES_REQUESTED** [review]
It looks like gnovm coverage went down 20%, we have to check why.

**Comment by gfanton** [comment]
I don't think we actually lost coverage, I think the reason why `gnovm` flag coverage is moving down by 20% is because by `txtar` also generate coverage for `tm2` packages. So the `gnovm` directory itself doesn't lost coverage, but by including `tm2` packages into `gnovm` flags we cover 20% less than gnovm packages only

`gnovm` flags **with** `txtar`  (from `gnovm/cmd/gno`) coverage:
image

`gnovm` flags **without** `txtar` (from `gnovm/cmd/gno`) coverage:
image

**Comment by gfanton** [comment]
@ajnavarro An idea to avoid having `gnovm` flags "corrupted" by `txtar` coverage, is to put `txtar` coverage under its own flag, such as `gnovm/txtar`.

**Comment by gfanton** [comment]
@ajnavarro should be good now

**Comment by ajnavarro** [comment]
IMO having txtar on its own coverage tag does not makes sense... A tag is defined per module we are testing, not by a group of tests...

What is specifically testing txtar? gnovm? tm2? gno node? a mix?
If we have a mix of tests testing different modules we should split them to be on these modules, if not it might be eventually a nightmare.

**Comment by gfanton** [comment]
i've added filtering by module so it doesn't expand coverage on multiple tags

**Review by ajnavarro — APPROVED** [review]

**Pull request merged**
