### PR TITLE
chore: In r/demo/boards public API, change AssertOriginCall() to PrevRealm().IsUser()

### PR DESCRIPTION
**Pull request by jefft0**
In r/demo/boards, `std.AssertOriginCall()` blocks calling the API from another realm. But it also prevents using MsgRun for testing as we do in PR #1583. Therefore, we change to check `std.PrevRealm().IsUser()`. This still blocks another realm from calling the code, but allows being [called by MsgRun](https://github.com/gnolang/gno/blob/d7f12167eff72cd4a12e9e8b8aaa30dc241bfb6c/misc/stress-test/stress-test-many-posts/main.go#L148-L156) where a user keypair sends the transaction.

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
</details>

### CODE REVIEW

**Comment by leohhhn** [comment]
@jefft0 can you please check why the tests are failing? 🙏

**Comment by jefft0** [comment]
Hi @leohhhn . A test file is getting the new panic message "invalid non-user call" when [calling the realm function](https://github.com/gnolang/gno/blob/e7e47d2589ceece37b0502d0df8d54ded582d501/examples/gno.land/r/demo/boards/z_2_filetest.gno#L21). I don't understand. I thought that `PrevRealm().IsUser()` is more permissive than `AssertOriginCall()`. If the test doesn't get a panic from `AssertOriginCall()`, then why get the new panic?

**Comment by jefft0** [comment]
> Hi @leohhhn . A test file is getting the new panic message "invalid non-user call" when [calling the realm function](https://github.com/gnolang/gno/blob/e7e47d2589ceece37b0502d0df8d54ded582d501/examples/gno.land/r/demo/boards/z_2_filetest.gno#L21). I don't understand. I thought that `PrevRealm().IsUser()` is more permissive than `AssertOriginCall()`. If the test doesn't get a panic from `AssertOriginCall()`, then why get the new panic?

Hi @leohhhn. I changed the test to `!(std.IsOriginCall() || std.PrevRealm().IsUser())` . Allowing `isOriginCall()` seems to make the tests happy. Is this the right way to do it?

**Comment by leohhhn** [comment]
@jefft0 

We should work with just `PrevRealm`. There is an API to set the caller realm in tests. [This is the docs for it](https://github.com/gnolang/gno/pull/2369) (in review), but there is currently an [issue](https://github.com/gnolang/gno/issues/2371) with the `TestSetRealm` function. 

Due to the issue, I suggest going with your latest proposal, and iterating on this once we fix up the issues.

**Review by leohhhn — APPROVED** [review]
LGTM for now

**Pull request merged**
