### PR TITLE
feat(ghverify): emit event when user request verification

### PR DESCRIPTION
**Pull request by Villaquiranm**
related to #2777 
<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Review by thehowl — COMMENTED** [review]
I'm not sure this is necessary. How does this event give more information to an off-chain user, if they could just use the indexer with this query?

```graphql
query {
  transactions(filter: {
    message: {
      route: vm,
      type_url: add_package,
      vm_param: {
        exec: {
          pkg_path: "gno.land/r/gnoland/ghverify",
          func: "RequestVerification"
        }
      }
  	}
  }) {
    hash
    messages {
      value {
        ... on MsgCall {
          args
        }
      }
    }
    gas_wanted
    success
    response {
      error
    }
  }
}
```

**Comment by leohhhn** [comment]
@thehowl 

We should always practice emitting events, even if we have an indexer.

**Comment by n0izn0iz** [comment]
if a realm (like a dao or an abstracted account) calls RequestVerification, it will be ignored by agents using your solution

**Review by thehowl — APPROVED** [review]

**Comment by thehowl** [comment]
After the discussion in #2777, I'm OK with the event being emitted - but I still think we need to use queries as a way to get the source of truth, and use events only as a pub/sub mechanism.

**Pull request merged**
