### PR TITLE
chore: update the getting started board's readme

### PR DESCRIPTION
**Pull request by moul**
Before this PR, the tutorial was a mix between local and remote commands.

I made changes to make it focused on onboarding new users without requiring to
run a local node.

### CODE REVIEW

**Comment by moul** [comment]
I just noticed that the doc was obviously intended to inform about how to publish smart contracts, so my change are probably not well located

**Comment by moul** [comment]
I just noticed that the doc was obviously intended to inform about how to publish smart contracts, so my change are probably not well located

**Comment by moul** [comment]
I’ve updated the PR, I think it’s a good getting started now

**Comment by moul** [comment]
And I published it to see it from the website https://gno.land/r/boards:gnolang/8

**Comment by jaekwon** [comment]
looks, great, i will change the website accordingly, thank you!

**Pull request merged**
