### PR TITLE
feat(gnovm/std): Add Alloc Usage features to std

### PR DESCRIPTION
**Pull request by thinhnx-var**
<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

As mentioned in #2070, because it's possible to pull various things from `MachineState`, this PR will:

1. Expose functions to get **Allocator Status** from the contracts.
2. Contract developers can create an `AllocTracker` to monitor memory allocation. This tracker utilizes the `Allocator.Status()` function and leverages the `Register()` and `Finish()` functions defined within the **AllocTracker** interface. Additionally, I've exposed a `GetResult()` function that internally calls Finish() and returns the resulting Allocated Usage information.

Simple contract example:

```
func DemoGetUsage() int64 {
	a := std.CreateATInstance()
	des := "test description"
	a.Register(des)

	// --- Do some stuffs ---

	a.Finish()
	return a.GetAllocUsage()
}

func DemoGetUsage2() int64 {
	a := std.CreateATInstance()
	des := "test description"
	a.Register(des)

	// --- Do some stuffs ---

	return a.GetResult()
}
```

I will update examples for this later if this PR is good enough to go.

I propose moving both `std.GasUsed()` (introduced in issue #1998 and implemented in pull request #2148) and this new function, `std.AllocatedMem()`, to the `runtime` package. This would facilitate the development of PProf-like profiling tools within Gno. I'll provide a more detailed proposal soon with the specific implementation details.

### CODE REVIEW

**Comment by thinhnx-var** [comment]
@thehowl 
I'd appreciate your feedback on this pull request at your earliest convenience.

**Comment by moul** [comment]
I would recommend:

- Not adding the new helpers and instead focusing on adding ways to measure performance without requiring userland solutions, such as using `gno test -cover`, `gno test -profile`, or a debugger.
- Alternatively, adding the new helpers but only for unit tests, such as `std.TestXXX...`.

The advantages of exposing these helpers for non-test runtime are not immediately clear.

**Comment by thinhnx-var** [comment]
@moul 
I am thinking about `go test -profile`. I will push a proposal for discussing about the output more to make it clearer.

**Comment by thinhnx-var** [comment]
related proposal here #2222

**Comment by thinhnx-var** [comment]
Closed due to adding `-print-runtime-metrics` flag.

**Pull request closed without merging**
