### PR TITLE
docs: add links into navbar

### PR DESCRIPTION
**Pull request by alexiscolin**
This PR aims to add following links into the docs website navbar: `Playground`, `blog` and `Gno.Land homepage`.

I chose to avoid setting GnoLand label as `home` in order to avoid a misunderstanding between `docs home` and `Gno.Land  home`. But we can discuss more about the label and its position here.

Close: #1527

### CODE REVIEW

**Review by thehowl — APPROVED** [review]
this lgtm, @waymobetta do you want this here or on https://github.com/gnolang/docs.gno.land ?

**Comment by thehowl** [comment]
>Would be great to see these changes without having to run locally. @albttx, can we set up deployment for PRs in case they handle docs, to have a preview?

Since the most interesting previews are going to be the visual ones like this one anyway, I suggest you start doing this after migrating to https://github.com/gnolang/docs.gno.land so that config can also be more straightforward. :)

**Comment by leohhhn** [comment]
Thanks @alexiscolin!

It seems to me that the "Back to Gno.land" text is of a diferent styling than the other text - can we make it the same for consistency?

**Review by leohhhn — APPROVED** [review]

**Review by zivkovicmilos — APPROVED** [review]

**Comment by albttx** [comment]
@alexiscolin can you move you PR to this repo please : https://github.com/gnolang/docs.gno.land

@leohhhn Yes i'll work on this once https://github.com/gnolang/docs.gno.land/pull/3/files merged

**Comment by albttx** [comment]
@thehowl should we close this ?

**Comment by alexiscolin** [comment]
@albttx  OK so do we agree this repo will not handle the docs shell anymore but only the content?

**Pull request merged**
