### PR TITLE
attempt to solve #591

### PR DESCRIPTION
**Pull request by grepsuzette**
this is a quick, provisional, WIP fix showing a solution for issue #591

when fields start with body, a textarea is used by realm_help instead of a linear input field.

# Description

# How has this been tested?
It's not functional yet. Graphically, the templates are ready:

Screenshot 2023-03-21 at 12-23-11 Gno land

However when you type anything in the textarea the command-line below is not updated.

### CODE REVIEW

**Comment by grepsuzette** [comment]
It should be ready for review.

# How was it tested 

The sequentiality was tested accessing the `?help` of a realm having this function:

`func FourFields(title string, body string, location string, body2 string) {}`

Screenshot 2023-03-21 at 13-19-28 Gno land
^ It updates in the right order.

**Comment by grepsuzette** [comment]
We should have tests for checking the consistency of umbrellaJs `.find()` function. 
With sequential fields, there is a world where umbrellaJs behaviour affects the security of the `?help` page.

**Comment by ajnavarro** [comment]
Hi @grepsuzette , could you rebase with master and resolve merging conflicts? after that, I think we can do a review pass. Thanks!

**Comment by grepsuzette** [comment]
Sorry, should have done a rebase, I'm closing here and going to open a new fix on top of master.

**Pull request closed without merging**
