### PR TITLE
build: update gnovm Makefile

### PR DESCRIPTION
**Pull request by notJoon**
Added stdlibs that were missing from `_test.gnoland.pkg0`

### CODE REVIEW

**Comment by moul** [comment]
would be nice to automate this, any idea?

**Comment by thehowl** [comment]
So, this one I'd jotted down to fix at some point; thank you for jumping ahead and doing it :)

My take on this:

- Let's split the tests into `TestPackages` and `TestPackagesLong`.
- `TestPackagesLong` tests `regexp` and `bytes`. Additionally, it is skipped on `t.Short()`
- `TestPackages`, instead, tests all packages in `stdlibs/*`, except for those tested by -Long.
- The Makefile is changed with the following
  - `_test.gnolang.pkg`: `-run '^TestPackages$'`
  - `_test.gnolang.pkg.bytes`: `-run '^TestPackagesLong$/^bytes'`
  - `_test.gnolang.pkg.regexp`: `-run '^TestPackagesLong$/^regexp'`. Note, this one should also test package `regexp/syntax`.

**Comment by notJoon** [comment]
> would be nice to automate this, any idea?

It would definitely be convenient to automate, but for now I can only think of scanning the directory with a shell script(like `find`) and then dynamically generating test targets. I'm sure there's a better way, but I'll have to look into it. 🤔

**Comment by thehowl** [comment]
>It would definitely be convenient to automate, but for now I can only think of scanning the directory with a shell script

You can just reorganise the tests (see my comment).

**Comment by zivkovicmilos** [comment]
Hey @notJoon,

Have you had the chance to implement @thehowl's suggestions?
I guess we can go ahead and merge this fix for now, and leave the test separation for a later PR

**Review by zivkovicmilos — APPROVED** [review]
Thank you for the fix 🙏

**Comment by thehowl** [comment]
ping @notJoon

**Comment by notJoon** [comment]
> ping @notJoon

Oh, I toatally forgot about this PR.

Is there anything else I need to work on? like the automation that we talked before.

**Comment by thehowl** [comment]
@notJoon see my comment for a proposal: https://github.com/gnolang/gno/pull/1371#issuecomment-1810496193

It requires adding an exception in code to simply split between "normal" and "long" packages; no automation / code-generation needed.

**Comment by notJoon** [comment]
> It requires adding an exception in code to simply split between "normal" and "long" packages; no automation / code-generation needed.

ah, I understand. I will add that ASAP

**Comment by notJoon** [comment]
> It requires adding an exception in code to simply split between "normal" and "long" packages; no automation / code-generation needed.

Yes, I've updated to based on your comment, and I'm currently working on fixing the tests that aren't passing. 

When I run it as an individual file it works fine, but when I run it with make I get the error `interface {} is nil, not std.ExecContext`. So, I'm trying to figure out why does it happend.

**Comment by thehowl** [comment]
>When I run it as an individual file it works fine, but when I run it with make

I don't see the tests you're running. Feel free to ping me in DM with stacktraces/info and I can take a look.

From the looks of it, the place where you think the error is happening may be incorrect. It should be somewhere where we're doing an assertion on `m.Context` (like in gnovm/stdlibs/std/*.go files).

**Comment by zivkovicmilos** [comment]
@notJoon Can you merge master into this branch, and check the CI?

Please see @thehowl's comments

**Comment by zivkovicmilos** [comment]
After discussing with @notJoon privately, we decided to close out this PR 🙏

**Pull request closed without merging**
