### PR TITLE
feat: add flag to execute filetests with prefix

### PR DESCRIPTION
**Pull request by deelawn**
This simply allows a prefix to be set when running filetests so that only a subset of tests are executed.  This is especially useful when a PR requires many new filetests -- it allows execution of all new tests without having to wait for ALL tests to run.

### CODE REVIEW

**Comment by ltzmaxwell** [comment]
can we also have this for txtar?

**Comment by deelawn** [comment]
> can we also have this for txtar?

We can but I'd prefer not to do it in this PR.

**Comment by piux2** [comment]
LGTM. 

can we add one or two examples to use the flag for filetests in the description?

**Comment by ltzmaxwell** [comment]
> > can we also have this for txtar?
> 
> We can but I'd prefer not to do it in this PR.

Yes, of course, 👍

**Comment by thehowl** [comment]
What's wrong with `-run 'TestFiles/^myprefix_`?

**Comment by deelawn** [comment]
> What's wrong with `-run 'TestFiles/^myprefix_'`?

Nothing is wrong with that.  It's just convenient for running tests and debugging.  VS Code allows to run tests from right in the editor, as well as running in debug mode so users can set certain breakpoints for a suite of tests. I found myself adding this locally multiple times when diagnosing various issues, so it would probably be useful to others as well.

**Comment by thehowl** [comment]
Skipping to avoid redundancy with -run.

**Pull request closed without merging**
