### PR TITLE
feat!: remove flag `-transpile` from `gno test`

### PR DESCRIPTION
**Pull request by harry-hov**
The `-transpile` flag in the `gno test` command duplicates the functionality of the standalone `gno transpile` command. Removed the unnecessary `-transpile` flag from the `gno test` command. 

`gno test` should only be focused on testing!

### CODE REVIEW

**Comment by thehowl** [comment]
cc @moul wdyt?

it seems that transpiling mostly served the purpose of attempting to build the transpiled go source; ie. static checking. though, effectively, this is moved to gno lint in https://github.com/gnolang/gno/pull/1730 . I tend to agree with @harry-hov to separate the concerns

**Comment by moul** [comment]
My goal with this flag was to have « gno test » exiting 0 of everything is OK and 1 of anything is bad.

‘before this flag, we basically had to run two commands to « test ».

ideally we should remove the flag but have a stronger type checking.

as soon as we’re testing to transpire on the CI, I’m fine removing the flag.

**Comment by harry-hov** [comment]
> ideally we should remove the flag but have a stronger type checking.

I agree. I think @thehowl is already working on this!

> as soon as we’re testing to transpire on the CI, I’m fine removing the flag.

We already have workflow for transpiling `/examples`
https://github.com/gnolang/gno/blob/5a64b2586148491777ae124aa984228df3d82e70/.github/workflows/examples.yml#L33

Infact we never run `gno test` with `-transpile` flag on CI.

**Comment by moul** [comment]
Let's remove the flag. Let's keep `transpile` in the CI and wait for stronger type checking to make `gno test` testing everything, as it should.

**Pull request merged**
