### PR TITLE
feat: Add Search Bar with Filter Functionality to Gnoweb

### PR DESCRIPTION
**Pull request by Olawale-22**
This PR implements a search bar with dynamic filtering functionality. It allows users to input search terms and dynamically filter content displayed on the page based on the input. If no match is found, only the header and footer are displayed. When no input is entered, the full content is rendered.

Key Changes:
Added a search bar component.
Implemented conditional content rendering based on search input.
Improved user navigation through filtered search results (Render filtering).
Adjusted the rendering logic to conditionally display content, the header, and footer based on the search results.
Tested the feature across various sections of the site to ensure stability and expected behavior.

Testing and Validation:
- Manually tested the feature to ensure correct behavior under various input scenarios.
- Validated that the page renders the entire content when no input is provided and correctly handles cases where no matches are found.
- No breaking changes were made, as no nodes was altered in the process (mainly javascript).

Contributors Checklist:

Tests made with special characters input to ensure nothing malicious may result from users input.

How to run:
Application is run using the (./build/gnoland start) and (./build/gnoweb -bind localhost:8888) commands or simply by running the 'start.sh' script in the root of the repo.

Next Steps:
Would be glad to make adjustments as needed based on further review and discussions. 
Would be looking into other issues moving forward in case of no further adjustment on filters.

Thank you for your consideration, and I look forward to your feedback!

### CODE REVIEW

**Comment by thehowl** [comment]
What is the advantage of this compared to Ctrl-F? (Browser's Find in Page?)

**Comment by Olawale-22** [comment]
> What is the advantage of this compared to Ctrl-F? (Browser's Find in Page?)

Hi @thehowl ,
It displays content based on search input, thereby simplifying what is rendered for easy and clear discovery of what it is being looked for. Could come in handy as the project grows larger.

**Review by thehowl — CHANGES_REQUESTED** [review]
Thank you for your contribution, but unfortunately this is not something we're looking for. Apologies for what @leohhhn wrote on #2877; but after also discussing with him we agreed that it's something that does not necessarily add much of value to the web interface; where really content can be searched with the browser's built-in features, in a way that also puts the found content into context, rather than removing all sorrounding elements.

So I'll be closing this and the related issue.

One thing we might look for eventually is a way to search through the rendered content; ie. implementing full-text-search on the gnoweb backend. However, keep in mind this is not something we want right now. It's a complex job which will require the dust on gnoweb to have settled down and various planned improvements to happen - see #1187. For now, it's a job best left to the search engine indexers.

Thanks nonetheless!

**Comment by Olawale-22** [comment]
> Thank you for your contribution, but unfortunately this is not something we're looking for. Apologies for what @leohhhn wrote on #2877; but after also discussing with him we agreed that it's something that does not necessarily add much of value to the web interface; where really content can be searched with the browser's built-in features, in a way that also puts the found content into context, rather than removing all sorrounding elements.
> 
> So I'll be closing this and the related issue.
> 
> One thing we might look for eventually is a way to search through the rendered content; ie. implementing full-text-search on the gnoweb backend. However, keep in mind this is not something we want right now. It's a complex job which will require the dust on gnoweb to have settled down and various planned improvements to happen - see #1187. For now, it's a job best left to the search engine indexers.
> 
> Thanks nonetheless!

Alright. I was quite working around and thought of some filters by the way, but yes I would be on the lookout for other issues to participate since #1187 is not available for new contributors if I understand perfectly.

Thanks for the review!

**Comment by thehowl** [comment]
@Olawale-22 everything on the repo is open for contributors by default.

we are planning a "gnoweb v2" which will be developed by the team; but some developments can be brought over to the new version if they are adaptable.

if there's something that piques your interest, please, comment on the issue and we'll try to evaluate if we can hand it off to you :)

**Comment by Olawale-22** [comment]
> @Olawale-22 everything on the repo is open for contributors by default.
> 
> we are planning a "gnoweb v2" which will be developed by the team; but some developments can be brought over to the new version if they are adaptable.
> 
> if there's something that piques your interest, please, comment on the issue and we'll try to evaluate if we can hand it off to you :)

Sounds great. would take a closer look on existing issues.

**Pull request closed without merging**
