### PR TITLE
chore(vscode): associate .gno files with Go syntax

### PR DESCRIPTION
**Pull request by qdm12**
# Description

1. Associate `*.gno` files with Go for syntax highlighting purposes in VSCode, through a repository-committed `.vscode/settings.json`.
1. Git ignore all files in the `.vscode` directory EXCEPT `.vscode/settings.json`

## Contributors Checklist

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests

## Maintainers Checklist

- [ ] Checked that the author followed the guidelines in `CONTRIBUTING.md`
- [ ] Checked the conventional-commit (especially PR title and verb, presence of `BREAKING CHANGE:` in the body)
- [ ] Ensured that this PR is not a significant change or confirmed that the review/consideration process was appropriate for the change

### CODE REVIEW

**Comment by thehowl** [comment]
I'm personally against having IDEs/text editor configurations inside code repos as I think they pollute the repository and create precedent for adding more in the future, but that's just my 2c.

Are you already using the Gno vs code extension? :)

**Comment by qdm12** [comment]
> I'm personally against having IDEs/text editor configurations inside code repos as I think they pollute the repository and create precedent for adding more in the future, but that's just my 2c.

Agreed, although it's nice to have a base specific to the repo I think 🤔 You can limit additions with PR review. Or we can close this, I just thought about sharing this.

> Are you already using the Gno vs code extension

No, shame on me, I'll try it! Maybe worth adding to that settings.json file instead of the syntax highlighting then?

**Comment by moul** [comment]
Let's prioritize updating `CONTRIBUTING.md` with instructions or creating configuration defaults in the `tools/` folder. It's important to maintain a clean and focused repository root with only essential content.

**Comment by qdm12** [comment]
I changed `.vscode/settings.json` -> `.vscode/extensions.json` with:

```json
{
  "recommendations": [
    "harry-hov.gno"
  ]
}
```

I would say this is nice since it doesn't conflict really with user specific vscode configuration like `.vscode/settings.json` does.

Back to that `tools/` folder, I don't think it exists, what did you have in mind for this? 🤔

**Comment by thehowl** [comment]
Thank you again for your contribution. After discussing this internally, we've decided not to include editor/ide-specific linters within our project. Relating to what @moul said, we already have the vs code extension as a suggestion in the `CONTRIBUTING.md` file, so I'll be closing this.

Possibly related discussion: https://github.com/gnolang/gno/issues/453 -- one thing that would be interesting to have is non-editor specific tools, eg. editorconfig. Thank you again for your time!

**Pull request closed without merging**
