### PR TITLE
make GNO copyleft/free software

### PR DESCRIPTION
**Pull request by jaekwon**
this makes GNO copyleft free software akin to the GNU Affero GPL v3 license.
this would apply to the gnolang vm. the other packages should remain published under Apache2.0.

### CODE REVIEW

**Comment by moul** [comment]
https://twitter.com/jaekwon/status/1594875770702159872?s=46&t=sw6P3bH4eZ_y8HzzpnZaCQ

**Comment by jaekwon** [comment]
TODO: make it clear that the rest is "Tendermint2", and under the Apache2 license.

**Comment by moul** [comment]
To make it clear, we can:

1. remove the top-level `LICENSE`.
2. create a top-level `COPYRIGHT` file explaining this with clear words.
3. create `LICENSE` files in each component's top-level directory.

**Comment by jaekwon** [comment]
How about we start using this? 

https://github.com/tendermint/tendermint2

**Comment by jaekwon** [comment]
Please don't merge this yet, adding a provision for allowing per-project additional restrictions, to enforce some type of attribution depending on the project....

**Review by moul — CHANGES_REQUESTED** [review]
Blocking the merge to avoid accidental merging before full review.

**Comment by jaekwon** [comment]
replace with #767

**Pull request closed without merging**
