### PR TITLE
fix: change board of quickstart guide

### LINKED ISSUE #220: bad command in the quickstart
Hello,
I noticed that in the [quickstart](https://gno.land/r/boards:gnolang/4) in the section "create a comment to a post", there was an omission in the first command.
In order to create a reply the command needs 4 args (boardid, threadid, postid and body) and not 3 as indicated in the post.

If you want I can create a new board quickstart and rectify the error before requesting the change in the code of the website.

Have a nice day

image
image

### PR DESCRIPTION
**Pull request by Doozers**
Change the link of old [quick start board](https://gno.land/r/boards:gnolang/4) to redirect on a board with the up to date [one](https://gno.land/r/boards:gnolang/191) based on the [README.md](https://github.com/gnolang/gno/blob/master/examples/gno.land/r/boards/README.md) avaliable in `examples/gno.land/r/boards/README.md`

Fixes #220

### CODE REVIEW

**Comment by moul** [comment]
Sorry, I wasn't clear in my other comment

I was asking to use GitHub diff's tool to show the difference in the post itself before checking if we want to just make an update (with a TX), or a PR which can be the one you did or another

**Comment by moul** [comment]
See #222 where I update the while I wanted that you update to get a way to discuss the change itself.

**Comment by moul** [comment]
Ok, I got it, you found the correct file but didn't want to change anything

Your issue was about the outdated version of gno.land, not about an outdated version of GitHub, sorry for the misunderstanding

As stated on #222, I need to wait for a redeploy of gno.land that support EditPost

Your solution requires a redeploy and will create a new URL, updating the existing post also requires a redeploy but has the advantage of not breaking the existing official link

**Comment by Doozers** [comment]
Yes for sure it looks like a much better solution, didn't know about the EditPost function, that's why I would have create a new post.
Have a nice day 👍

**Comment by moul** [comment]
Yep, and I relly appreciate the initiative :)

**Pull request closed without merging**
