### PR TITLE
grocksdb

### PR DESCRIPTION
**Pull request by faddat**
- adds support for rocksdb v7 using the linxGnu/grocksdb go wrapper
- preserves support for rocksdb v6 using the tecbot/gorocksdb go wrapper

### CODE REVIEW

**Comment by jaekwon** [comment]
thanks Jacob. just curious, are you using rocksdb, or should we?

**Comment by faddat** [comment]
The main line is badly out of date

The benchmarks are kind of all over the place, and for some things, rocks is much faster for example queries.

I think that my preference is likely pebble because of the level of active development on that project but I have had some interesting conversations with the terra team recently about bolt

I’m starting to think that we may be able to find a way to synchronize these chains using IPFS cids and that would be greatly preferable

**Comment by faddat** [comment]
happy to do it that way.

Personally I do think cgo is a problem (this is from feedback from terra and some benchmarks I played with-- basically extra cpu usage vs pure go),  as is having too many kv store choices, but hey why not?

it is surely not the biggest problem in the world by any means.

**Comment by faddat** [comment]
anyhow, between this and #150 -- should give gnomes a bit of an idea about the additional challenges of supporting cgo libs.  

The docker image used in the ci job, is made hourly at faddat/archlinux-docker

**Comment by faddat** [comment]
@jaekwon the short answer?

yeah cgo is a problem :)

**Comment by jaekwon** [comment]
Ok thank you for that context. One more thing... can we please revert the go.mod changes, to help minimize dependencies? We can change the target DB at any time and change mod then. I'm not sure how else to best manage the go.mod bloat.

**Comment by faddat** [comment]
That's a really good idea.  

Have you thought at all about focusing on a single db?

My preference right now is pebbledb.  

It:

* no cgo
* no facebook (rocks)
* no unmaintained (goleveldb)

Marko from the SDK team mentioned that it's possible to do a lot more optomization when using just a single db, and I tend to agree with him.  

Then the database layer can be less of an adapter and a bit more specalized around gno's needs.  Since we won't be using cgo, we won't hit the same kinds of dx issues that we would otherwise.

**Comment by jaekwon** [comment]
Let's figure that out later some time before launch. For now I'll merge these changes by way of #196, and we can figure it out later and make it the default. I agree that goleveldb probably isn't optimal.

**Pull request closed without merging**
