### PR TITLE
fix(gonative):  add constant information when we define a go native value

### PR DESCRIPTION
**Pull request by omarsy**
First part of the fix: https://github.com/gnolang/gno/issues/2836

The second part is addressed here: https://github.com/gnolang/gno/pull/2731

### CODE REVIEW

**Review by thehowl — COMMENTED** [review]
I think all values declared using gonative should be not modifiable.

Can we just have that if you have an assignment on a value which is statically typed as a native value, you cannot change it?

**Comment by omarsy** [comment]
> I think all values declared using gonative should be not modifiable.
> 
> Can we just have that if you have an assignment on a value which is statically typed as a native value, you cannot change it?

We have an example of editing a native value here: https://github.com/gnolang/gno/blob/master/gnovm/tests/files/assign0b_native.gno. I'm unsure if this is something we want to prohibit.

**Comment by thehowl** [comment]
The fact that values are modifiable makes functions modifiable, too:

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Sprintf = func(v string, p ...interface{}) string { return "123" }
	println(fmt.Sprintf("a", "b"))
}
```

Seeing as we eventually want to remove gonative (#1361), I think it's sensible to remove the ability to modify these entirely.

**Comment by omarsy** [comment]
Yes maybe we should forbid the edit only for functions and constants. WDYT ?

**Comment by omarsy** [comment]
Added here: https://github.com/gnolang/gno/pull/2848/commits/0671c8832884b0937cd131826c81b8efca5899dc

Nice catch for the issue ^^

**Review by thehowl — APPROVED** [review]

**Pull request merged**
