### PR TITLE
feat(examples): Add Nemanya's Home Realm to Examples

### PR DESCRIPTION
**Pull request by Nemanya8**
## Overview

This home realm allows users to donate GNOT to support Web3 projects, with dynamic content updates, text art, and a sponsor leaderboard. The code is easy to understand and copy, making it a great example. It also serves as an informative introduction to myself for ecosystem users.

## Key Features:

- **Text Art Rendering:**
  - Introduced a feature to display text art in codeblocks, offering a visually appealing and customizable way to present content on the home realm page.

- **Content Customization:**
  - Admin can easily update the contents of the page, including sections like "About Me," "Sponsor Information," and social media links, giving them full control over the realm’s presentation.
  
- **GNOT Donation System for Projects:**
  - Integrated a GNOT donation system, enabling users to sponsor specific Web3 projects. Donations are displayed on the project pages, showcasing the support of the community.

- **Sponsor Tracking and Display:**
  - Added functionality to track and display the sponsors for each project, allowing donors to see the impact of their contributions.

## Realm appearance

image
image

### CODE REVIEW

**Comment by Gno2D2** [comment]
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)
- [ ] The pull request description provides enough details


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 The pull request was created from a fork (head branch repo: Nemanya8/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

<details><summary>The pull request description provides enough details</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 Not (🔴 Pull request author is a member of the team: core-contributors)

```
### Can be checked by
 - team core-contributors

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

**Review by leohhhn — APPROVED** [review]

**Comment by leohhhn** [comment]
I clicked "IGNORE" on the bot because I reviewed the PR and it looks good.

**Comment by n0izn0iz** [comment]
It looked good but broke CI :P

**Comment by moul** [comment]
#3415

**Comment by leohhhn** [comment]
Not sure how; the CI was broken it seems - it was not red in this PR.

**Pull request merged**
