### PR TITLE
feat(paginate): re-open PR with #883's work

### PR DESCRIPTION
**Pull request by Doozers**
<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Comment by Doozers** [comment]
@tbruyelle tried to modify the previous PR's target branch via github but this created a strange merge commit so as mentionned by @thehowl I will continue here

**Comment by tbruyelle** [comment]
I think it would be better to migrate your `p/demo/md` package into `/p/demo/ui`. 
- `md.Link` can be removed because it already exists as `ui.Link` 
- `md.EscMDURL` should be turned into a private function in `p/demo/ui` and used internally in `ui.Link.Render()`.

**Comment by tbruyelle** [comment]
> Hi @tbruyelle tried to modify the previous PR's target branch via github but this created a strange merge commit so as mentionned by @thehowl I will continue here

Let's close the previous PR then.

**Comment by Doozers** [comment]
> I think it would be better to migrate your `p/demo/md` package into `/p/demo/ui`.
> 
> * `md.Link` can be removed because it already exists as `ui.Link`
> * `md.EscMDURL` should be turned into a private function in `p/demo/ui` and used internally in `ui.Link.Render()`.

yes better this way 👍

**Review by tbruyelle — APPROVED** [review]
LGTM

**Comment by jefft0** [comment]
Hello @Doozers . There is a new PR for pagination from moul. https://github.com/gnolang/gno/pull/2584 . Do you want to close this PR in favor of that one?

**Comment by jefft0** [comment]
Hello @tbruyelle . You approved this pagination PR a year ago. Now there is a new PR from moul with two approvals. https://github.com/gnolang/gno/pull/2584 . Should this PR be closed in favor of the new one?

**Comment by tbruyelle** [comment]
> Hello @tbruyelle . You approved this pagination PR a year ago. Now there is a new PR from moul with two approvals. #2584 . Should this PR be closed in favor of the new one?

Well, tbh, right now I don't have the time to dive into this code a year after I first looked at it, but I trust that moul has done a better job, so yeah, let's close this PR.

**Pull request closed without merging**
