### PR TITLE
chore(ci): setup docker build cache

### PR DESCRIPTION
**Pull request by albttx**
Build docker images as test, and let it for developers

### CODE REVIEW

**Comment by albttx** [comment]
After mutliple tries, i'm not sure it's improve a lot the build time.

probably because it's concurrent build.

**Comment by zivkovicmilos** [comment]
@albttx can you please update the branch to the latest `master` and resolve conflicts? 🙏

**Comment by albttx** [comment]
@zivkovicmilos So i fixed / rebased this PR, and added a workflow that didn't push the Docker image (this can be remove if you want).

The idea is to add a simple dockerfile that could be use by dev (because the goreleaser version require the go toolchain locally, this is a more "pure" docker image where the binaries are built inside the images.

This Dockerfile is require for me for the ci/portal-loop test!

**Comment by Kouteki** [comment]
> @zivkovicmilos is this still relevant?

@sw360cab @zivkovicmilos the question still stands :)

**Comment by sw360cab** [comment]
@Kouteki  I am working on a template of optimized image in the dedicated gno infra repository

**Comment by albttx** [comment]
This PR can be close

**Pull request closed without merging**
