### PR TITLE
fix(gnoweb): update "airgapped" commands in realm help page

### PR DESCRIPTION
**Pull request by thehowl**
This matches `gnokey sign`'s behaviour to the updated version from #1976. I've manually tested this on a local node, and it works.

### CODE REVIEW

**Comment by moul** [comment]
Can you add a `txtar` file named `gnoweb-airgapped.txtar` so we have a regression test that will automatically fail if we break CLI compatibility again?

In addition, this will allow me to reuse the `txtar` logic that uses stdout.

**Comment by moul** [comment]
Btw, I think that #1976 removes the possibility to sign the same tx twice, with two different accounts from CLI.

**Comment by thehowl** [comment]
@moul done; some fine tuning to get there as not all commands in gnokey were actually using `io` as intended.

**Comment by thehowl** [comment]
> Btw, I think that #1976 removes the possibility to sign the same tx twice, with two different accounts from CLI.

yes, I have some doubts about what the PR did as well. I've asked milos to clarify, but we may end up changing some behaviour again.

**Review by leohhhn — APPROVED** [review]

**Pull request merged**
