### PR TITLE
feat(mod): utilize `~/.gno` dir

### PR DESCRIPTION
**Pull request by harry-hov**
Related: #462 

See discussion: https://github.com/gnolang/gno/pull/479#discussion_r1090356338

### CODE REVIEW

**Comment by thehowl** [comment]
Mhhh. I personally dislike it when software create a new directory in my $HOME. I would rather they used `~/.local/share/` or `~/.cache`.

I don't know if this conversation was already had previously, but if we're extending the use of GNO_HOME, I think we should consider having it elsewhere?

**Comment by moul** [comment]
What about following other standards such as the XDG_ and other well-known environment variables, in order to adhere to best practices on various systems and allow users to override the default value if desired?

**Comment by moul** [comment]
This PR does not involve creating a new folder, but rather reusing the existing one that is created and used globally for gno.

Let's take a closer look at @harry-hov's work for this addition which is finally more as a merge + making gno more independent from go in terms of FS (which is good IMO). Then reevaluate if we should pursue a different approach for managing config-dirs globally. @thehowl, what are your thoughts on my previous comment?

**Review by moul — APPROVED** [review]
LGTM for the PR

We would like to ensure that @thehowl's valid concern is addressed before merging, for example, by inserting or updating issues.

**Comment by thehowl** [comment]
@moul Created #655 for that

**Review by thehowl — APPROVED** [review]

**Pull request merged**
