### PR TITLE
chore: more concise PR template

### PR DESCRIPTION
**Pull request by moul**
- skip one redundant title
- make the top suggestion a comment instead of plain text

<details><summary>Contributor checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](../.benchmarks/README.md).
</details>

### CODE REVIEW

**Comment by harry-hov** [comment]
Can we do something about broken links in last point of the checklist?
> [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/.benchmarks/README.md).

**Review by harry-hov — APPROVED** [review]

**Comment by moul** [comment]
I've been thinking about removing that line since it's rarely addressed. My suggestion is to include a dedicated paragraph in the contribution guidelines and open an issue to discuss adding more useful benchmarks. What do you think?

**Comment by harry-hov** [comment]
I think it's okay to remove it. The links are broken anyways. (we can always add things back if needed)

Sorry, I don't have much context about this point and I'm not sure what exactly contributors are supposed to do. 
But, can we automate the benchmarking process instead of asking contributors to do it?

**Review by albttx — APPROVED** [review]

**Comment by ajnavarro** [comment]
My comments, opinions, and explanations of whys here:
- :+1: to move the explanation about adding the description to a comment. That info is still visible to the PR author, and you do not need to delete that part of the template.
- :-1: to keep checks inside a summary tag: why? Checks are there for a reason, and adding a way to ignore them is not the way to go IMHO. Checks are there to remember people's tasks that cannot be automated and must be done on every PR. These checks help the author not forget anything and help the reviewer to make a more straightforward due diligence process, based on trust in the author.
- :-1: to remove benchmark check: I would love to be able to "automate" benchmarks. If someone has a good idea to do it, that would be awesome. The first link is broken because we were waiting until having a custom action runner to be able to run the tests (that is why the reports are not generated yet giving us a 404). That part is almost done by @albttx , so that link will eventually be working. The second link is a relative one, and that seems to not work on templates. Created a PR fixing it: https://github.com/gnolang/gno/pull/1005. Even if right now is not a common thing to do, is something I would encourage (that check is encouraging it). Benchmarks are really important to validate ideas and new developments, and they will give us enormous insights into how code evolves through time. @harry-hov : here you have more context about that check: https://github.com/gnolang/gno/pull/881

**Pull request merged**
