### PR TITLE
feat(mux): support query string in path

### PR DESCRIPTION
**Pull request by x1unix**
This PR adds support for request URLs with query strings for `p/demo/mux` package.

Previously, `mux.Router` would fail to find a correct handler if request URL contains query string.

```go
r := mux.NewRouter()
r.HandleFunc("hello", func (rw *mux.ResponseWriter, req *mux.Request) {
  ...
})

reqUrl := "hello?foo=bar"
r.Render(reqUrl) // Fails
```

This PR fixes this behavior and introduces a new `mux.Request.RawPath` field which contains a raw request path including query string.

The `RawPath` field is designed to be used for packages like `p/demo/avl/pager` to extract query params from a string.\
The `Path` field, as before, contains just path segment of request, without query strings.

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
</details>

CC @moul @thehowl @jeronimoalbi

### CODE REVIEW

**Comment by Gno2D2** [comment]
I'm a bot that assists the Gno Core team in maintaining this repository. My role is to ensure that contributors understand and follow our guidelines, helping to streamline the development process.

The following requirements must be fulfilled before a pull request can be merged.
Some requirement checks are automated and can be verified by the CI, while others need manual verification by a staff member.

These requirements are defined in this [configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

## Automated Checks

 🔴 Maintainers must be able to edit this pull request
 🔴 The pull request head branch must be up-to-date with its base


## Manual Checks

- [ ] The pull request description provides enough details


<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Then
```
🔴 Requirement not satisfied
└── 🔴 Maintainer can modify this pull request

```
</blockquote></details>

<details><summary>The pull request head branch must be up-to-date with its base</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Then
```
🔴 Requirement not satisfied
└── 🔴 Head branch (gnostudio:devx/feature/mux-router-improvements) is up to date with base (master): behind by 1 / ahead by 1

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>The pull request description provides enough details</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 Not (🔴 Pull request author is a member of the team: core-contributors)

```
### Can be checked by
 - team core-contributors

</blockquote></details>

</blockquote></details>

</blockquote></details>

**Review by moul — APPROVED** [review]
LGTM

I still consider that we should rename `p/mux` into `p/router`; what do you think?

Edit: Never mind, I remember that I chose `mux` because it mimics the `http.Mux` object with the `ResponseWriter`. Let's keep it named `mux` for now, and we can eventually extract the `router` part into a minimal `router` package if you're only interested in pure parsing. This can be done later.

**Review by petar-dambovaliev — APPROVED** [review]

**Review by leohhhn — APPROVED** [review]
I assume we will get some weird edge cases that fail; but this is an upgrade that is needed for multiple packages, so let's fix along the way.

**Review by thehowl — APPROVED** [review]

**Comment by thehowl** [comment]
related #2876

**Pull request merged**
