### PR TITLE
fix(gnovm): show "out of gas" errors (#2365)

### LINKED ISSUE #2365: out of gas error is unclear `(VM call panic {WritePerByte})`
The same kind of bug as #1205 but with `{WritePerByte}` has been happening quite a lot, when adding packages with insufficient gas.

```
Data: internal error
Msg traces:
    0 /me/gno/tm2/pkg/crypto/keys/client/maketx.go:213 - deliver transaction failed: log:recovered: strings/strings.gno:11: {WritePerByte}
stack: see below
```
<details><summary>Call stack</summary>
<pre>
stack:
goroutine 53 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x5e
github.com/gnolang/gno/tm2/pkg/sdk.(*BaseApp).runTx.func1()
        /me/gno/tm2/pkg/sdk/baseapp.go:749 +0x205
panic({0xf1e340?, 0xc005525a80?})
        /usr/lib/go/src/runtime/panic.go:770 +0x132
go/types.(*Checker).handleBailout(0xc0071f1c00, 0xc005317760)
        /usr/lib/go/src/go/types/check.go:367 +0x88
panic({0xf1e340?, 0xc005525a80?})
        /usr/lib/go/src/runtime/panic.go:770 +0x132
github.com/gnolang/gno/gnovm/pkg/gnolang.predefineNow.func1()
        /me/gno/gnovm/pkg/gnolang/preprocess.go:3070 +0x25c
panic({0xf6ba00?, 0xc005525a40?})
        /usr/lib/go/src/runtime/panic.go:770 +0x132
github.com/gnolang/gno/tm2/pkg/store/types.(*basicGasMeter).ConsumeGas(0x45bcfc?, 0x31?, {0x108d47d?
, 0x457969?})
        /me/gno/tm2/pkg/store/types/gas.go:97 +0x68
github.com/gnolang/gno/tm2/pkg/store/gas.(*Store).Set(0xc00479a060, {0xc0035b97c0, 0x31, 0x40}, {0xc
005556640, 0x12e, 0x12e})
        /me/gno/tm2/pkg/store/gas/store.go:45 +0x103
github.com/gnolang/gno/gnovm/pkg/gnolang.(*defaultStore).SetObject(0xc0004560a0, {0x13e25d8, 0xc0052
98280})
        /me/gno/gnovm/pkg/gnolang/store.go:323 +0x30f
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Realm).saveObject(0x13c7528?, {0x13e4940, 0xc0004560a0}, 
{0x13e25d8, 0xc005298280})
        /me/gno/gnovm/pkg/gnolang/realm.go:747 +0x12b
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Realm).saveUnsavedObjectRecursively(0xc0003c60e0, {0x13e4
940, 0xc0004560a0}, {0x13e25d8, 0xc005298280})
        /me/gno/gnovm/pkg/gnolang/realm.go:702 +0xf9
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Realm).saveUnsavedObjectRecursively(0xc0003c60e0, {0x13e4
940, 0xc0004560a0}, {0x13e23c8, 0xc003d1ab00})
        /me/gno/gnovm/pkg/gnolang/realm.go:691 +0xc5
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Realm).saveUnsavedObjectRecursively(0xc0003c60e0, {0x13e4
940, 0xc0004560a0}, {0x13e25d8, 0xc0052990e0})
        /me/gno/gnovm/pkg/gnolang/realm.go:691 +0xc5
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Realm).saveUnsavedObjectRecursively(0xc0003c60e0, {0x13e4
940, 0xc0004560a0}, {0x13e24d0, 0xc0006a4750})
        /me/gno/gnovm/pkg/gnolang/realm.go:691 +0xc5
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Realm).saveUnsavedObjectRecursively(0xc0003c60e0, {0x13e4
940, 0xc0004560a0}, {0x13e28f0, 0xc0070d1680})
        /me/gno/gnovm/pkg/gnolang/realm.go:691 +0xc5
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Realm).saveUnsavedObjects(0xc0003c60e0, {0x13e4940, 0xc00
04560a0})
        /me/gno/gnovm/pkg/gnolang/realm.go:651 +0x96
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Realm).FinalizeRealmTransaction(0xc0003c60e0, 0xe8?, {0x1
3e4940, 0xc0004560a0})
        /me/gno/gnovm/pkg/gnolang/realm.go:334 +0xb9
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).savePackageValuesAndTypes(0xc007f2d8c8)
        /me/gno/gnovm/pkg/gnolang/machine.go:662 +0x10f
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).runMemPackage(0xc007f2d8c8, 0xc007162d00, 0x1, 0
x0)
        /me/gno/gnovm/pkg/gnolang/machine.go:291 +0x246
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).RunMemPackage(...)
        /me/gno/gnovm/pkg/gnolang/machine.go:255
github.com/gnolang/gno/gno.land/pkg/sdk/vm.(*VMKeeper).initBuiltinPackagesAndTypes.func1({0xc002ca34
57, 0x7}, {0x13e4940, 0xc0004560a0})
        /me/gno/gno.land/pkg/sdk/vm/builtins.go:40 +0x245
github.com/gnolang/gno/gnovm/pkg/gnolang.(*defaultStore).GetPackage(0xc0004560a0, {0xc002ca3457, 0x7
}, 0x77?)
        /me/gno/gnovm/pkg/gnolang/store.go:170 +0x125
github.com/gnolang/gno/gnovm/pkg/gnolang.tryPredefine({0x13e4940, 0xc0004560a0}, {0x13e17a0, 0xc004f
42908}, {0x13d7548, 0xc004a2b480})
        /me/gno/gnovm/pkg/gnolang/preprocess.go:3226 +0x163
github.com/gnolang/gno/gnovm/pkg/gnolang.predefineNow2({0x13e4940, 0xc0004560a0}, {0x13e17a0, 0xc004
f42908}, {0x13d7548, 0xc004a2b480}, 0xc005316408)
        /me/gno/gnovm/pkg/gnolang/preprocess.go:3090 +0x130
github.com/gnolang/gno/gnovm/pkg/gnolang.predefineNow({0x13e4940, 0xc0004560a0}, {0x13e17a0, 0xc004f
42908}, {0x13d7548, 0xc004a2b480})
        /me/gno/gnovm/pkg/gnolang/preprocess.go:3075 +0x153
github.com/gnolang/gno/gnovm/pkg/gnolang.PredefineFileSet({0x13e4940, 0xc0004560a0}, 0xc004f42c08, 0
xc004b82330)
        /me/gno/gnovm/pkg/gnolang/preprocess.go:43 +0x6f5
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).runFiles(0xc0002f8008, {0xc004f2cd00, 0x5, 0x8})
        /me/gno/gnovm/pkg/gnolang/machine.go:530 +0x275
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).RunFiles(...)
        /me/gno/gnovm/pkg/gnolang/machine.go:496
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).runMemPackage(0xc0002f8008, 0xc0047fc480, 0x1, 0
x0)
        /me/gno/gnovm/pkg/gnolang/machine.go:287 +0x22d
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).RunMemPackage(...)
        /me/gno/gnovm/pkg/gnolang/machine.go:255
github.com/gnolang/gno/gno.land/pkg/sdk/vm.(*VMKeeper).initBuiltinPackagesAndTypes.func1({0xc002c85c
81, 0x7}, {0x13e4940, 0xc0004560a0})
        /me/gno/gno.land/pkg/sdk/vm/builtins.go:40 +0x245
github.com/gnolang/gno/gnovm/pkg/gnolang.(*defaultStore).GetPackage(0xc0004560a0, {0xc002c85c81, 0x7
}, 0x10?)
        /me/gno/gnovm/pkg/gnolang/store.go:170 +0x125
github.com/gnolang/gno/gnovm/pkg/gnolang.(*defaultStore).getMemPackage(0xc0004560a0, {0xc002c85c81, 
0x7}, 0x0)
        /me/gno/gnovm/pkg/gnolang/store.go:558 +0xbd
github.com/gnolang/gno/gnovm/pkg/gnolang.(*defaultStore).GetMemPackage(0xc007fc0c48?, {0xc002c85c81?
, 0xc002c85c81?})
        /me/gno/gnovm/pkg/gnolang/store.go:545 +0x1a
github.com/gnolang/gno/gnovm/pkg/gnolang.(*gnoImporter).ImportFrom(0xc00452f740, {0xc002c85c81, 0x7}
, {0xc007fc0cc8?, 0x22acd8?}, 0x7?)
        /me/gno/gnovm/pkg/gnolang/go2gno.go:540 +0x64
go/types.(*Checker).importPackage(0xc0071f1c00, {0x13c3a00, 0xc00452faa0}, {0xc002c85c81, 0x7}, {0x1
3b6c68, 0x1})
        /usr/lib/go/src/go/types/resolver.go:158 +0x53a
go/types.(*Checker).collectObjects.func1({0x13c3b80?, 0xc003f0a960})
        /usr/lib/go/src/go/types/resolver.go:267 +0x125
go/types.(*Checker).walkDecl(0xc0071f1c00, {0x13c9fa0?, 0xc0046f4940}, 0xc005317658)
        /usr/lib/go/src/go/types/decl.go:412 +0x2e7
go/types.(*Checker).walkDecls(...)
        /usr/lib/go/src/go/types/decl.go:399
go/types.(*Checker).collectObjects(0xc0071f1c00)
        /usr/lib/go/src/go/types/resolver.go:254 +0xe2f
go/types.(*Checker).checkFiles(0xc0071f1c00, {0xc002e5b7c0, 0x6, 0x9})
        /usr/lib/go/src/go/types/check.go:405 +0x17c
go/types.(*Checker).Files(...)
        /usr/lib/go/src/go/types/check.go:372
go/types.(*Config).Check(0xc00479a180, {0xc00038ff68?, 0xa?}, 0xc0046f4600, {0xc002e5b7c0, 0x6, 0x9}
, 0x0)
        /usr/lib/go/src/go/types/api.go:458 +0x79
github.com/gnolang/gno/gnovm/pkg/gnolang.(*gnoImporter).parseCheckMemPackage(0xc00452f740, 0xc0046f4
500)
        /me/gno/gnovm/pkg/gnolang/go2gno.go:574 +0x366
github.com/gnolang/gno/gnovm/pkg/gnolang.TypeCheckMemPackage(0xc0046f4500, {0x762c507f8570, 0xc00045
60a0})
        /me/gno/gnovm/pkg/gnolang/go2gno.go:505 +0x14c
github.com/gnolang/gno/gno.land/pkg/sdk/vm.(*VMKeeper).AddPackage(_, {{0x13cba08, 0xc003eb7b00}, 0x2
, {0x13cac60, 0xc003a46a50}, {0x13cbd50, 0xc0004694a0}, {0xc000e5fa7b, 0x3}, ...}, ...)
        /me/gno/gno.land/pkg/sdk/vm/keeper.go:166 +0x545
github.com/gnolang/gno/gno.land/pkg/sdk/vm.vmHandler.handleMsgAddPackage({_}, {{0x13cba08, 0xc003eb7
b00}, 0x2, {0x13cac60, 0xc003a46a50}, {0x13cbd50, 0xc0004694a0}, {0xc000e5fa7b, 0x3}, ...}, ...)
        /me/gno/gno.land/pkg/sdk/vm/handler.go:44 +0xb8
github.com/gnolang/gno/gno.land/pkg/sdk/vm.vmHandler.Process({_}, {{0x13cba08, 0xc003eb7b00}, 0x2, {
0x13cac60, 0xc003a46a50}, {0x13cbd50, 0xc0004694a0}, {0xc000e5fa7b, 0x3}, ...}, ...)
        /me/gno/gno.land/pkg/sdk/vm/handler.go:31 +0x358
github.com/gnolang/gno/tm2/pkg/sdk.(*BaseApp).runMsgs(_, {{0x13cba08, 0xc003eb7b00}, 0x2, {0x13cac60
, 0xc003a46a50}, {0x13cbd50, 0xc0004694a0}, {0xc000e5fa7b, 0x3}, ...}, ...)
        /me/gno/tm2/pkg/sdk/baseapp.go:650 +0x2ed
github.com/gnolang/gno/tm2/pkg/sdk.(*BaseApp).runTx(0xc000422700, 0x2, {0xc0046e4000, 0x1bc2, _}, {{
0xc0038eb990, 0x1, 0x1}, {0x895440, {{0xc002c84dc2, ...}, ...}}, ...})
        /me/gno/tm2/pkg/sdk/baseapp.go:829 +0xae5
github.com/gnolang/gno/tm2/pkg/sdk.(*BaseApp).DeliverTx(0xc000422700, {{}, {0xc0046e4000?, 0x0?, 0x0
?}})
        /me/gno/tm2/pkg/sdk/baseapp.go:585 +0x15d
github.com/gnolang/gno/tm2/pkg/bft/abci/client.(*localClient).DeliverTxAsync(0xc000415320, {{}, {0xc
0046e4000, 0x1bc2, 0x1bc2}})
        /me/gno/tm2/pkg/bft/abci/client/local_client.go:82 +0xeb
github.com/gnolang/gno/tm2/pkg/bft/appconn.(*consensus).DeliverTxAsync(0x0?, {{}, {0xc0046e4000?, 0x
0?, 0x0?}})
        /me/gno/tm2/pkg/bft/appconn/app_conn.go:74 +0x23
github.com/gnolang/gno/tm2/pkg/bft/state.execBlockOnProxyApp(0xc00005a260, {0x13d1bc0, 0xc000412d50}
, 0xc004bbdd40, {0x13d7458, 0xc0003bdd20})
        /me/gno/tm2/pkg/bft/state/execution.go:265 +0x557
github.com/gnolang/gno/tm2/pkg/bft/state.(*BlockExecutor).ApplyBlock(_, {{0x108bc64, 0xb}, {0x108bc6
4, 0xb}, {0x0, 0x0}, {0xc00031cacb, 0x3}, 0x49, ...}, ...)
        /me/gno/tm2/pkg/bft/state/execution.go:102 +0x17a
github.com/gnolang/gno/tm2/pkg/bft/consensus.(*ConsensusState).finalizeCommit(0xc0000fe608, 0x4a)
        /me/gno/tm2/pkg/bft/consensus/state.go:1370 +0x88c
github.com/gnolang/gno/tm2/pkg/bft/consensus.(*ConsensusState).tryFinalizeCommit(0xc0000fe608, 0x4a)
        /me/gno/tm2/pkg/bft/consensus/state.go:1294 +0x190
github.com/gnolang/gno/tm2/pkg/bft/consensus.(*ConsensusState).enterCommit.func1()
        /me/gno/tm2/pkg/bft/consensus/state.go:1240 +0x88
github.com/gnolang/gno/tm2/pkg/bft/consensus.(*ConsensusState).enterCommit(0xc0000fe608, 0x4a, 0x0)
        /me/gno/tm2/pkg/bft/consensus/state.go:1271 +0xa25
github.com/gnolang/gno/tm2/pkg/bft/consensus.(*ConsensusState).addVote(0xc0000fe608, 0xc0062a25a0, {
0x0, 0x0})
        /me/gno/tm2/pkg/bft/consensus/state.go:1684 +0x785
github.com/gnolang/gno/tm2/pkg/bft/consensus.(*ConsensusState).tryAddVote(0xc0000fe608, 0x417dba?, {
0x0?, 0x762c503ec268?})
        /me/gno/tm2/pkg/bft/consensus/state.go:1518 +0x2f
github.com/gnolang/gno/tm2/pkg/bft/consensus.(*ConsensusState).handleMsg(0xc0000fe608, {{0x13c3600, 
0xc00041f320}, {0x0, 0x0}})
        /me/gno/tm2/pkg/bft/consensus/state.go:696 +0xf8
github.com/gnolang/gno/tm2/pkg/bft/consensus.(*ConsensusState).receiveRoutine(0xc0000fe608, 0x0)
        /me/gno/tm2/pkg/bft/consensus/state.go:655 +0x452
created by github.com/gnolang/gno/tm2/pkg/bft/consensus.(*ConsensusState).OnStart in goroutine 1
        /me/gno/tm2/pkg/bft/consensus/state.go:349 +0x4ef
</pre>
</details> 

Sometimes adding the same package and with the same gas settings I simply get 

```
Data: std.OutOfGasError{abciError:std.abciError{}}
Msg Traces:
    0  /me/gno/tm2/pkg/std/errors.go:106 - out of gas in location: txSize; gasWanted: 9000, gasUsed: 71110
Stack Trace:
    0  /me/gno/tm2/pkg/errors/errors.go:20
    1  /me/gno/tm2/pkg/std/errors.go:106
    2  /me/gno/tm2/pkg/sdk/auth/ante.go:87
    3  /usr/lib/go/src/runtime/panic.go:770
    4  /me/gno/tm2/pkg/store/types/gas.go:97
    5  /me/gno/tm2/pkg/sdk/auth/ante.go:108
    6  /me/gno/gno.land/pkg/gnoland/app.go:104
    7  /me/gno/tm2/pkg/sdk/baseapp.go:806
    8  /me/gno/tm2/pkg/sdk/baseapp.go:569
    9  /me/gno/tm2/pkg/bft/abci/client/local_client.go:90
   10  /me/gno/tm2/pkg/bft/appconn/app_conn.go:115
   11  /me/gno/tm2/pkg/bft/mempool/clist_mempool.go:286
   12  /me/gno/tm2/pkg/bft/mempool/clist_mempool.go:214
   13  /me/gno/tm2/pkg/bft/rpc/core/mempool.go:230
   14  /usr/lib/go/src/reflect/value.go:596
   15  /usr/lib/go/src/reflect/value.go:380
   16  /me/gno/tm2/pkg/bft/rpc/lib/server/handlers.go:185
   17  /me/gno/tm2/pkg/bft/rpc/lib/server/handlers.go:209
   18  /usr/lib/go/src/net/http/server.go:2166
   19  /usr/lib/go/src/net/http/server.go:2683
   20  /me/code/go/pkg/mod/github.com/rs/cors@v1.10.1/cors.go:281
   21  /usr/lib/go/src/net/http/server.go:2166
   22  /me/gno/tm2/pkg/bft/rpc/lib/server/http_server.go:216
   23  /me/gno/tm2/pkg/bft/rpc/lib/server/http_server.go:189
   24  /usr/lib/go/src/net/http/server.go:2166
   25  /usr/lib/go/src/net/http/server.go:3137
   26  /usr/lib/go/src/net/http/server.go:2039
   27  /usr/lib/go/src/runtime/asm_amd64.s:1695
```

### Steps to reproduce

* `gnodev -minimal`
```
gnokey maketx addpkg -pkgpath "gno.land/p/demo/mux" \
                -pkgdir "examples/gno.land/p/demo/mux" \
                -deposit 10ugnot \
                -gas-fee 10ugnot \
                -gas-wanted 9000000 \
                -broadcast=true \
                -chainid "dev" \
                -remote "127.0.0.1:26657" \
                bob 
```

Edit: Note from commit f2844 onwards (#2504), the above method can't seem to reproduce this bug.

### PR DESCRIPTION
**Pull request by grepsuzette**
The following should fix #2365 when adding a package.

### Problem

#2365 (and before it, #1205) described a way where adding packages with insufficient gas very often lead to hard to read errors such as:
```
Data: internal error
Msg traces:
    0 /me/gno/tm2/pkg/crypto/keys/client/maketx.go:213 - deliver transaction failed: log:recovered: strings/strings.gno:11: {WritePerByte}
```

### Diagnostic

Using the call stack in #2365, the following seems to happen. 

While preprocessing some file, a panic with `OutOfGasException` occurs:
https://github.com/gnolang/gno/blob/e7e47d2589ceece37b0502d0df8d54ded582d501/tm2/pkg/store/types/gas.go#L96-L98

Upper level recovers and repanics with error:
https://github.com/gnolang/gno/blob/e7e47d2589ceece37b0502d0df8d54ded582d501/gnovm/pkg/gnolang/preprocess.go#L3057-L3070

Upper level treats it as a banal error (falling in `default:` rather than `OutOfGasException`, this snippet is longer, make sure to scroll down):
https://github.com/gnolang/gno/blob/e7e47d2589ceece37b0502d0df8d54ded582d501/tm2/pkg/sdk/baseapp.go#L733-L752

###  Proposed fix

Just add a couple of lines in gno/gnovm/pkg/gnolang/preprocess.go:
```go
func predefineNow(store Store, last BlockNode, d Decl) (Decl, bool) {
	defer func() {
		if r := recover(); r != nil {
			// before re-throwing the error, append location information to message.
			loc := last.GetLocation()
			if nline := d.GetLine(); nline > 0 {
				loc.Line = nline
			}
			if rerr, ok := r.(error); ok {
				// NOTE: gotuna/gorilla expects error exceptions.
				panic(errors.Wrap(rerr, loc.String()))
+			} else if ex, ok := r.(OutOfGasException); ok {
+                panic(ex)
            } else {
				// NOTE: gotuna/gorilla expects error exceptions.
				panic(fmt.Errorf("%s: %v", loc.String(), r))
			}
		}
	}()
	m := make(map[Name]struct{})
	return predefineNow2(store, last, d, m)
}
```

After recompiling and testing with the modus operandi described in #2365, the error message is now:
```
Data: out of gas error
Msg Traces:
    0  /me/gno/tm2/pkg/crypto/keys/client/maket
x.go:213 - deliver transaction failed: log:out of gas, gasWanted: 9000000, gasUsed: 9001550 location: WritePerByte
```
Repeatedly calling with fresh `gnodev -minimal` each time and adding package now consistently shows this message.

### Discussion
 
There still remains a question about the "NOTE: gotuna/gorilla expects error exceptions".

Think it has to do with gnoweb ability to print failures, e.g. `gnoweb` uses `func makeRequest(log *slog.Logger, cfg *Config, qpath string, data []byte) (res *abci.ResponseQuery, err error)`.

However `BaseApp.runTx` will turn the OutOfGasException to a nice `ABCIError(std.ErrOutOfGas())`.
So, in theory, it should do. 

I will do some more test tonight adding many packages from `/p/demo`.

### CODE REVIEW

**Comment by ltzmaxwell** [comment]
just curious, is it only happening with `predefineNow()`?

**Comment by grepsuzette** [comment]
> just curious, is it only happening with predefineNow()?
I am not sure, that's why I will try to add many packages.

**Comment by grepsuzette** [comment]
Tested by manually adding all the packages in `/p/demo/`, respecting dependencies. I didn't find a problem except the second time calling addpkg with low gas (#2453), hence "Draft".

But #2453 happens whether or not this PR was applied.

**Comment by Kouteki** [comment]
Fixes https://github.com/gnolang/gno/pull/2368

**Review by thehowl — COMMENTED** [review]
Can you add a test (I'd say txtar test is better here) which currently leads to an unclear error, but then returns an appropriate message?

Also, I think it's better if, instead of having this at the level of preprocess, we switched the type assertion in keeper.go to use `errors.As` instead.

`tm2/pkg/errors` supports the standard Unwrap function, so errors.As should work here.

**Comment by grepsuzette** [comment]
> Can you add a test (I'd say txtar test is better here) which currently leads to an unclear error, but then returns an appropriate message?

Yep, however this [issue2365.txtar.txt](https://github.com/user-attachments/files/16247807/issue2365.txtar.txt) now seems rather pointless,
as I can not reproduce the issue. Did a git bisect and it doesn't happen since #2504.

**Comment by thehowl** [comment]
> > Can you add a test (I'd say txtar test is better here) which currently leads to an unclear error, but then returns an appropriate message?
> 
> Yep, however this [issue2365.txtar.txt](https://github.com/user-attachments/files/16247807/issue2365.txtar.txt) now seems rather pointless, as I can not reproduce the issue. Did a git bisect and it doesn't happen since #2504.

Probably related to changing gas values?

Try lowering the `-gas-wanted`. It should hit the gas limit when we're still in Preprocess. Off the top of my head, we should still be hitting the gas counter while Preprocessing, so this fix should still be valid.



> Took a look, think you mean here, in `func (vm *VMKeeper) AddPackage(ctx, msg) error`:

Okay, I think I understand why it was happening here. With lazy stdlib loading (before #2504), GetPackage could be called by the type checker, invoking a `Preprocess`. Now it cannot happen anymore, so at least in that case if there is a OutOfGas panic it should just return correctly.

I think more generally we can hit this condition if there is an OutOfGas panic in predefine (and consequently, Preprocess). Both predefine and Preprocess capture and wrap errors. So it's good if we catch any out of gas errors and unwrap them.

So what I'm suggesting is to change all blocks like this one in keeper.go:

```
		if r := recover(); r != nil {
			switch r.(type) {
			case store.OutOfGasException: // panic in consumeGas()
				panic(r)
			default:
				err = errors.Wrap(fmt.Errorf("%v", r), "VM run main addpkg panic: %v\n%s\n",
					r, m.String())
				return
			}
		}

```

to use errors.As instead of the type assertion; so it should be able to return a correct error in case of a Preprocess OutOfGas.

**Comment by grepsuzette** [comment]
> Probably related to changing gas values?
Tried a variety of gas values buit since #2504 it's only the regular "out of gas error" that is shown. 

> Okay, I think I understand why it was happening here. With lazy stdlib loading (before #2504), GetPackage could be called by the type checker, invoking a `Preprocess`. Now it cannot happen anymore, so at least in that case if there is a OutOfGas panic it should just return correctly.

Thanks, good explanation! It explains what I observed:  much lower gas consumption (2-3 times less), and no seemingly unrelated panics anymore when running out of gas. 

> I think more generally we can hit this condition if there is an OutOfGas panic in predefine (and consequently, Preprocess). Both predefine and Preprocess capture and wrap errors. So it's good if we catch any out of gas errors and unwrap them.

Think we may be able to reproduce #2365 in non-testing cases (on-chain): 
```go
func (vm *VMKeeper) Initialize(
	logger *slog.Logger,
	ms store.MultiStore,
	cacheStdlibLoad bool,
) {
	if vm.gnoStore != nil {
		panic("should not happen")
	}
	baseSDKStore := ms.GetStore(vm.baseKey)
	iavlSDKStore := ms.GetStore(vm.iavlKey)

	if cacheStdlibLoad {
		// Testing case (using the cache speeds up starting many nodes)
		vm.gnoStore = cachedStdlibLoad(vm.stdlibsDir, baseSDKStore, iavlSDKStore)
	} else {
		// On-chain case
		vm.gnoStore = uncachedPackageLoad(logger, vm.stdlibsDir, baseSDKStore, iavlSDKStore)   // <-- HERE
	}
}
```
I'm now wondering if we could configure the boolean cacheStdlibLoad from within txtar. 
Since txtar is about testing chain stuffs, I think it would make sense.
Or perhaps there is already an environment/directory where txtar would run on a non-testing chain already.

**Comment by grepsuzette** [comment]
`gnodev` itself runs a TestConfig() environment, https://github.com/gnolang/gno/blob/5083bcb6f4410c9e2a40d35416690ffbf84f64ce/contribs/gnodev/pkg/dev/node.go#L45-L46

https://github.com/gnolang/gno/blob/5083bcb6f4410c9e2a40d35416690ffbf84f64ce/gno.land/pkg/gnoland/node_inmemory.go#L54-L58

Which again explains bug is irreproducible using txtar or gnodev.

**Comment by grepsuzette** [comment]
> to use errors.As instead of the type assertion; so it should be able to return a correct error in case of a Preprocess OutOfGas.

Sorry but I disagree with you :)  (after spending a lot of time, I could still be wrong mind you).

We are not supposed to do anything with OutOfGasException., Just re-panicking them until the top-level (baseapp) converts them to `ABCIError(std.ErrOutOfGas(..))`:

As we can see here, at the top-level of the app, the formatting of out of gas errors happens, with the consumed quantities and so on:
https://github.com/gnolang/gno/blob/5083bcb6f4410c9e2a40d35416690ffbf84f64ce/tm2/pkg/sdk/baseapp.go#L727-L749

Furthermore, `OutOfGasException` seem to volontarily not have been made into errors, precisely because they are a special type of panic with an exclusive pathway to the top-level. 

So in my opinion, things like this are exactly what should be done:
```go
case store.OutOfGasException: // panic in consumeGas()
				<re-panic>
```
There's nothing to touch here in my opinion. 

-----

Since the txtar just works now, and since the TypeCheckMemPackage won't run anymore when adding package (IIUC), 
also since #2365 (which this PR was supposed to fix) is closed as non-reproducible, think this can be closed, say in a few days.

**Comment by grepsuzette** [comment]
> I think more generally we can hit this condition if there is an OutOfGas panic in predefine (and consequently, Preprocess). Both predefine and Preprocess capture and wrap errors. So it's good if we catch any out of gas errors and unwrap them.

Perhaps this is the part which I didn't understand though. OK! Think I know what you mean now.

**Comment by thehowl** [comment]
Do you think you can find a case where this bug happens?

I expect this to be replicable with low gas values; like between 5k and 500k.

**Comment by grepsuzette** [comment]
> Do you think you can find a case where this bug happens?
> 
> I expect this to be replicable with low gas values; like between 5k and 500k.

I already tried with like 20 different low values the other day. Besides, after #2504 it would not happen in this case (`addpkg`), would it? We could try to sweep a range incrementally, if it's worth it (i.e.  still theoretically possible).

**Review by piux2 — COMMENTED** [review]
I reproduced it and fixed it in a separate PR https://github.com/gnolang/gno/pull/2638

**Pull request closed without merging**
