### PR TITLE
ci: publish master Docker images without `--snapshot` flag

### PR DESCRIPTION
**Pull request by ajnavarro**

### CODE REVIEW

**Comment by thehowl** [comment]
#3010

workflow before it: https://github.com/gnolang/gno/actions/runs/11487457417/job/31972052132

**Comment by ajnavarro** [comment]
@thehowl  can we add a dummy v0.0.0 tag to stop this back and forth?

**Comment by thehowl** [comment]
maybe let's run `git tag v0.0.0 6ff6762d6` ahead of running goreleaser.

**Comment by ajnavarro** [comment]
@thehowl done

**Review by thehowl — APPROVED** [review]

**Pull request merged**
