### PR TITLE
feat(examples): add disperse

### PR DESCRIPTION
**Pull request by leohhhn**
## Description

This PR adds a port of the [Disperse.app ](https://disperse.app/) smart contract on EVM. It helps showcase how sending GNOT to and from a realm works. 

This PR is part of the Dogfooding initiative. [Here](https://github.com/gnolang/devrel/issues/24#issuecomment-1832038944) is the linking comment. 

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Comment by leohhhn** [comment]
This PR is currently blocked by the inability to write tests:
- `gno test` does not work correctly with the banker API (a larger issue)
- txtar tests do not currently provide enough configuration - for testing the Disperse app, there needs to be multiple accessible addresses within the testing context, and currently the only accessible one is test1.

**Comment by zivkovicmilos** [comment]
> This PR is currently blocked by the inability to write tests:
> 
> * `gno test` does not work correctly with the banker API (a larger issue)
> * txtar tests do not currently provide enough configuration - for testing the Disperse app, there needs to be multiple accessible addresses within the testing context, and currently the only accessible one is test1.
> 
> @moul @thehowl @deelawn @zivkovicmilos - how can we progress on making the testing experience better?

I'm not sure what the exact problem is with using txtar for an e2e test. What kind of data do you need in the test?

**Comment by thehowl** [comment]
> * txtar tests do not currently provide enough configuration - for testing the Disperse app, there needs to be multiple accessible addresses within the testing context, and currently the only accessible one is test1.

Two proposals:

1. Adding proper support for adding a key to the keystore, ie. being able to call `gnokey add` and pass in the mnemonic in txtar. (Reqires changing txtar up a bit)
2. Using gnokey import/export (I think this can be done now already)

**Comment by thehowl** [comment]
One more thing: it seems to me that you don't actually _need_ to create the accounts you claim you need to create (from the current state of the code).

That is, unless they need to be able to move coins on their own, the accounts don't need to have a matching private key.

You can just use disperse to send off tokens to some account strings you made up, and then check the txtar result of doing `gnokey query auth/accounts/%s`.

**Comment by leohhhn** [comment]
Update on this: this has been sitting for a ton of time. Will get back to it soon hopefully, it's not a priority right now.

**Pull request closed without merging**
