### PR TITLE
fix: replace old realm path to current one

### PR DESCRIPTION
**Pull request by r3v4s**
# Description

Function was using old user realm path which doesn't have 'demo' string in path.

# Additional
There are bunch of test files(`z_*_filetest.gno`) with old realm path, should I update all of it?

### CODE REVIEW

**Comment by r3v4s** [comment]
> 



> I can be wrong but I think it's the inverse actually, `r/users` is the old one, and `r/demo/users` is the current one.

Yes you're right, did I mis guide something?

**Review by moul — APPROVED** [review]

**Review by moul — CHANGES_REQUESTED** [review]
unit tests are probably outdated

**Comment by thehowl** [comment]
> I can be wrong but I think it's the inverse actually, `r/users` is the old one, and `r/demo/users` is the current one.

Exactly, the PR seems to me to be right though.

@r3v4s Do you want to finish this and update the unit tests? No problem if you don't, I'll close this and make another PR

**Review by moul — APPROVED** [review]

**Comment by r3v4s** [comment]
I'll finish it :D

**Comment by leohhhn** [comment]
Hey @r3v4s, what's the status on this?

**Comment by r3v4s** [comment]
> Hey @r3v4s, what's the status on this?

oops, sorry. forgot to make it ready for review after ci successful

**Review by zivkovicmilos — APPROVED** [review]

**Pull request merged**
