### PR TITLE
feat: add support for private key exports

### PR DESCRIPTION
**Pull request by zivkovicmilos**
# Description

This PR adds support for exporting private keys from the key-base, using the `gnokey export` command.

The private key armor that is saved is encrypted using a passphrase that the user sets.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist (for contributors)

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [x] I have added sufficient documentation in code

# Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

## Manual tests

Tested manually by invoking the command:
```bash
gnokey export --key MyKey --output-path ./mykey.asc
```

Additionally, a new unit test has been added for covering this functionality.

# Additional comments
There should be an `import` command also available, that knows how to do the opposite of export.
I'll add this functionality in a separate PR.

### CODE REVIEW

**Review by moul — APPROVED** [review]

**Comment by r3v4-onbloc** [comment]
Hello @zivkovicmilos, this is Blake from Onbloc, building Adena wallet.

We're trying to implement import/export functionality in our wallet that's compatible with gnokey (and furthermore another wallet like Keplr & Metamask)

However we notice that this pr inlcudes only encrypted export functionality, and isn't compatible with the existing wallets so it'll be inconvenient for users to import/export keys.

So my question is, do you have plan to add something like `--unsafe`, `--unarmored-hex` in gnokey like gaiad does?

**Comment by zivkovicmilos** [comment]
Hey @r3v4-onbloc,

The only reason we kept the encrypted armor functionality is to keep up with existing keybase code (it expects to work with encrypted keys). 

I honestly see no issue with adding unencrypted export / import functionality for keys (if the user asks for it explicitly) - it should be pretty straightforward to do. I'll open up a PR and link you as soon as I have it up. 

Just to confirm - you need unencrypted private key armor export / import?

**Comment by r3v4-onbloc** [comment]
Yes we do. Thank you for your comment and future implementation.

**Comment by zivkovicmilos** [comment]
No problem, I'll ping you once it's up and ready for viewing

**Comment by zivkovicmilos** [comment]
@r3v4-onbloc [PR](https://github.com/gnolang/gno/pull/537) is out 🚀

**Pull request merged**
