### PR TITLE
Website: remove wording

### PR DESCRIPTION
**Pull request by michelleellen**
Replace Gno Studio with Gno IDE

### CODE REVIEW

**Comment by ajnavarro** [comment]
Hey! I think the provided changes are not the expected ones. Ping me if you need any help.

**Comment by alexiscolin** [comment]
I'm gonna take care of this one 👍

**Comment by alexiscolin** [comment]
@michelleellen Can you close this PR? Here is the new one: https://github.com/gnolang/www.gno.land/pull/14

**Comment by michelleellen** [comment]
This PR is no longer necessary

**Pull request closed without merging**
