### PR TITLE
chore: use -coverpkg for extended code coverage reports

### PR DESCRIPTION
**Pull request by moul**
As discussed during the review meeting.

h/t @thehowl.

### CODE REVIEW

**Comment by thehowl** [comment]
Some weird results:

image

Any idea why some tests seem to show "decreasing coverage"?

also/ it looks like the YAML from the last PR is invalid: https://app.codecov.io/gh/gnolang/gno/commit/f49e9d03077f7661619791e52a5112d70ea019d9

@moul I saw in the last codecov PR you were complaining about not being able to validate the YAML until merged into master. They actually support validation, but you must do it through a HTTP request to their server:

```console
curl --data-binary @/dev/stdin https://codecov.io/validate << EOF
codecov:
  notify:
    wait_for_ci: false

ignore:
  - misc

comment:
  require_changes: true
[...]
EOF
Error at ['codecov', 'require_changes']:
unknown field
```

**Comment by moul** [comment]
> @moul I saw in the last codecov PR you were complaining about not being able to validate the YAML until merged into master. They actually support validation, but you must do it through a HTTP request to their server:

Thanks, but I was not talking about validation, but checking the impact of the change itself.

**Comment by moul** [comment]
See #1139

**Comment by thehowl** [comment]
I suspect the pkg1 and pkg2 tests to be failing because enabling coverage reporting on so many packages probably slows them down too much (adding the flag rewrites the code in order to count the lines covered). Obviously we have an issue of the two tests being too slow in general, but I think we might still improve our coverage data with what we actually test by having `-coverpkg` on `gnovm/pkg/gnolang` for all tests of package `gnovm/tests`. (Additionally, the same would probably need to be done for txtar, but we can add that later)

**Comment by thehowl** [comment]
https://github.com/gnolang/gno/pull/1220#issuecomment-2020384791

**Pull request closed without merging**
