### PR TITLE
chore(gnokey): add newline when showing data from `query` 

### PR DESCRIPTION
**Pull request by leohhhn**
## Description

This PR adds a newline to make the data display of queries a bit nicer.

Before:
```
> gnokey query vm/qfile -data "gno.land/r/demo/wugnot" -remote https://rpc.gno.land:443
height: 0
data: wugnot.gno
z0_filetest.gno
```

After:

```
> gnokey query vm/qfile -data "gno.land/r/demo/wugnot" -remote https://rpc.gno.land:443
height: 0
data:
wugnot.gno
z0_filetest.gno
```

Similar case for other queries.

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [x] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Comment by jefft0** [comment]
Hi @leohhhn . Do you want to merge master to see if it fixes some of the failing CI tests?

**Comment by jefft0** [comment]
@leohhhn , can you fix the failed CI test for "Go Test / test"? It's failing because your commit changes the expected output for "data:". For example:
```
            FAIL: testdata/event_multi_msg.txtar:10: no match for `data: {` found in stdout
```

**Comment by jefft0** [comment]
Sill have CI tests that fail due to expected output.

**Comment by jefft0** [comment]
Removed the `review/triage-pending` label because the original author changed this PR to draft. When it is ready, we can add the label again.

**Comment by leohhhn** [comment]
Closing as we won't be needing this.

**Pull request closed without merging**
