### PR TITLE
feat: added os.Args to native values (gnolang#930)

### PR DESCRIPTION
**Pull request by salihdhaifullah**
- [ ] Add tests
- [ ] Find a way to parse args
<details>
<summary>

</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
</details>

### CODE REVIEW

**Comment by moul** [comment]
What is the end goal of this PR?

**Comment by jefft0** [comment]
Removed the "review team" label because moul already responded.

**Comment by salihdhaifullah** [comment]
To implement the first part of [930](https://github.com/gnolang/gno/issues/930)

**Comment by salihdhaifullah** [comment]
I am not sure how to implement args parsing

**Comment by thehowl** [comment]
Thanks for the PR; I think we want something different for os.Args - see my last comment on https://github.com/gnolang/gno/issues/930 . Thanks!

**Pull request closed without merging**
