### PR TITLE
chore: `s/Gno.land/gno.land/g`

### PR DESCRIPTION
**Pull request by thehowl**
some locations were missed, most importantly on gnoweb.

changes also involve changing the hiring link, which was pointing to lever which we don't use anymore, and prettifying the html pages. this was done automatically by my text editor; I can revert it if we want a cleaner diff.

### CODE REVIEW

**Comment by leohhhn** [comment]
Repo description as well - been looking at it for some time now but cannot change it myself.

Screenshot 2024-10-30 at 13 43 35

**Comment by thehowl** [comment]
cc @moul (see leon's comment)

**Review by moul — APPROVED** [review]

**Comment by moul** [comment]
Fixed.

**Comment by leohhhn** [comment]
Same goes for the gnolang org description: https://github.com/gnolang

**Review by leohhhn — APPROVED** [review]

**Pull request merged**
