### PR TITLE
WIP: Generate .proto files using amino/genproto

### PR DESCRIPTION
**Pull request by jaekwon**
This will let protobuf serialization be used instead of native amino reflection.
In the future, we will write our own serialization logic generator.
For now, we translate the native go type into protobuf generated go type, and back.

### CODE REVIEW

**Comment by pyramation** [comment]
LGTM!

I tested and merged the latest protos, and documented the process for generating client code from the protos here

https://github.com/pyramation/gnojs#for-developers-building-gnojs

**Comment by jaekwon** [comment]
not quite done yet...

**Comment by giansalex** [comment]
I should have seen this before, but I was able to create a valid tx, using custom [proto files](https://github.com/disperze/gnojs-types/blob/master/proto/gnoland/tx/tx.proto)

**Comment by jaekwon** [comment]
closing in favor of https://github.com/gnolang/gno/pull/199, after rebase.

**Pull request closed without merging**
