### PR TITLE
fix(gnovm): handle case of NumStmts = 0 when creating stacktraces

### PR DESCRIPTION
**Pull request by thehowl**
without the patch, the test fails with this error:

```
--- FAIL: TestTestdata (1.97s)
    --- FAIL: TestTestdata/issue_outofgas_stacktrace (1.97s)
        testscript.go:558: # test for a bug involving printing stacktraces with missing statements;
            # when dumping out information for a test. (1.763s)
            > loadpkg gno.land/p/demo/avl
            "gno.land/p/demo/avl" package was added to genesis
            > gnoland start
            [stdout]
            node started successfully
            
            > ! gnokey maketx addpkg -pkgdir $WORK -pkgpath gno.land/r/pkg1 -gas-fee 1000000ugnot -gas-wanted 10000000 -broadcast -chainid=tendermint_test test1
            [stdout]
            TX HASH:    sMuFd6oGIxmMHuY1HLbVm6Mi30Nq6cF7mBC5Rt0chug=
            
            [stderr]
            Enter password.
            "gnokey" error: --= Error =--
            Data: runtime error: index out of range [-1]
            Msg Traces:
                0  /home/howl/oc/gno/tm2/pkg/crypto/keys/client/maketx.go:215 - deliver transaction failed: log:msg:0,success:false,log:--= Error =--
            Data: &errors.errorString{s:"runtime error: index out of range [-1]"}
            Msg Traces:
                0  /home/howl/oc/gno/gno.land/pkg/sdk/vm/keeper.go:386 - VM addpkg panic: runtime error: index out of range [-1]
            Machine:
                CheckTypes: false
                Op: [OpHalt OpPopResults]
                Values: (len: 1)
                      #0 (init.2 func()())
                Exprs:
                Stmts:
                Blocks:
                      @(50) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00a4c6b40,Source:func init.2() { for i<VPBlock(1,...,Parent:0xc00a17cd20)
             (s vals) @(50) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc0060b0830,Source:func init.2() { for i<VPBlock(1,...,Parent:0xc0091d9230)
             (s typs) @(50) []
                      @(156) Block(ID:302e5163ca42d53def527ea18dfd0ca4ce3602ba:5,Addr:0xc00a17cd20,Source:file{ package hello; import strc...,Parent:0xc011300780)
                        strconv: (package(strconv strconv) package{})
                        avl: (package(avl gno.land/p/demo/avl) package{})
             (s vals) @(156) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc0091d9230,Source:file{ package hello; import strc...,Parent:0xc0091d9530)
                        strconv: (package(strconv strconv) package{})
                        avl: (package(avl gno.land/p/demo/avl) package{})
             (s typs) @(156) [package{} package{}]
                Blocks (other):
                      #1 Block(ID:302e5163ca42d53def527ea18dfd0ca4ce3602ba:5,Addr:0xc00a17cd20,Source:file{ package hello; import strc...,Parent:0xc011300780)
                        strconv: (package(strconv strconv) package{})
                        avl: (package(avl gno.land/p/demo/avl) package{})
             (static) #1 Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc0091d9230,Source:file{ package hello; import strc...,Parent:0xc0091d9530)
                        strconv: (package(strconv strconv) package{})
                        avl: (package(avl gno.land/p/demo/avl) package{})
                Frames:
                      #0 [FRAME FUNC:init.2 RECV:(undefined) (0 args) 2/0/0/0/2 LASTPKG:gno.land/r/pkg1 LASTRLM:Realm{Path:"gno.land/r/pkg1",Time:4003}#302E5163CA42D53DEF527EA18DFD0CA4CE3602BA]
                Realm:
                  gno.land/r/pkg1
                Exceptions:
            
            
            Stack Trace:
                0  /home/howl/oc/gno/tm2/pkg/errors/errors.go:20
                1  /home/howl/oc/gno/gno.land/pkg/sdk/vm/keeper.go:386
                2  /home/howl/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/panic.go:770
                3  /home/howl/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/panic.go:114
                4  /home/howl/oc/gno/gnovm/pkg/gnolang/machine.go:482
                5  /home/howl/oc/gno/gnovm/pkg/gnolang/machine.go:793
                6  /home/howl/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/panic.go:770
                7  /home/howl/oc/gno/tm2/pkg/store/types/gas.go:97
                8  /home/howl/oc/gno/tm2/pkg/store/gas/store.go:46
                9  /home/howl/oc/gno/gnovm/pkg/gnolang/store.go:449
               10  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:747
               11  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:714
               12  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               13  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               14  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               15  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               16  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               17  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               18  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               19  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               20  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               21  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               22  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               23  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               24  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               25  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               26  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               27  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               28  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               29  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               30  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
               31  /home/howl/oc/gno/gnovm/pkg/gnolang/realm.go:703
            --= /Error =--
            ,events:[]
            --= /Error =--
            
            
            > stderr 'out of gas'
            FAIL: testdata/issue_outofgas_stacktrace.txtar:9: no match for `out of gas` found in stderr
            
FAIL
exit status 1
FAIL	github.com/gnolang/gno/gno.land/cmd/gnoland	2.001s
```

### CODE REVIEW

**Comment by thehowl** [comment]
cc @omarsy, if you can also take a look.

**Review by omarsy — APPROVED** [review]
LGTM, but  I'm wondering if is it necessary to include the realm's stack trace if we have an OutOfGasException?

**Comment by thehowl** [comment]
> LGTM, but I'm wondering if is it necessary to include the realm's stack trace if we have an OutOfGasException?

no, and it's not printed, but it was trying to create it anyway. i think the stacktrace is created, but eventually not used.

**Comment by Gno2D2** [comment]
I'm a bot that assists the Gno Core team in maintaining this repository. My role is to ensure that contributors understand and follow our guidelines, helping to streamline the development process.

The following requirements must be fulfilled before a pull request can be merged.
Some requirement checks are automated and can be verified by the CI, while others need manual verification by a staff member.

These requirements are defined in this [configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

## Automated Checks

 🔴 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
 🟢 The pull request head branch must be up-to-date with its base ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch))


## Manual Checks

*No manual checks match this pull request.*

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Then
```
🔴 Requirement not satisfied
└── 🔴 Maintainer can modify this pull request

```
</blockquote></details>

<details><summary>The pull request head branch must be up-to-date with its base (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Head branch (dev/morgan/stackframe-dump) is up to date with base (master): behind by 0 / ahead by 4

```
</blockquote></details>

</blockquote></details>



</blockquote></details>

**Pull request closed without merging**
