### PR TITLE
fix: deprecate std.GetOrigCaller

### PR DESCRIPTION
**Pull request by n0izn0iz**
Screenshot 2024-10-04 at 18 44 53

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Comment by n0izn0iz** [comment]
from @leohhhn 
> Might sound weird coming from me, but we should possibly keep it. i've found a few occasions where i found it useful. 
We should have PrevRealm or its equivalent as the primary, non-limiting choice, while keeping OriginCaller as a specific functionality, discouraging it unless the user really knows what they're doing.
checkout RegisterCode(): https://gno.land/r/gc24/raffle/raffle.gno

What is the advantage or GetOrigCaller vs taking the address as input?

**Comment by thehowl** [comment]
For stdlibs, we'll err on the side of caution and add things after launch if necessary. So, relating to Leon's point, I'd remove it then add it back if necessary.

**Comment by leohhhn** [comment]
@n0izn0iz 

> What is the advantage or GetOrigCaller vs taking the address as input?

The difference is that the developer can enforce this rule. If the address was an input, the user could put in any random address.

In my specific example, I needed the realm calling my realm to be deployed by the same user that did some other action. This specific case I've seen a couple of times.

**Comment by n0izn0iz** [comment]
@leohhhn wdyt about getting the user address by inspecting the `PrevRealm()` pkg path and calling `users.Resolve` if it's a namespace?

**Review by moul — CHANGES_REQUESTED** [review]
Blocking to prevent merging until the necessary discussions have taken place.

**Comment by thehowl** [comment]
We'll actually be keeping GetOriginCaller for now: https://github.com/gnolang/gno/issues/1475#issuecomment-2463442177

Thanks!

**Pull request closed without merging**
