### PR TITLE
fix(website): use better regexp to support any depth (#564)

### LINKED ISSUE #564: website doesn't work with arbitrarily deep packages
Simply put, it works with a simple depth e.g. `r/demo/foo.gno`.

It is possible to addpkg to `r/demo/very/deep/foo.gno`.
and it renders adequately with `gnokey query vm/qeval (...)`.

But visiting `http://127.0.0.1:8888/r/very/deep` won't Render. It can be confusing for users in general.

Working on a PR.

### PR DESCRIPTION
**Pull request by grepsuzette**
This allows arbitrarily deep packages.

# Description

Fixes #564
Website used to work with a simple depth packages like `demo/foo`. But not with `very/deep/foo`. 

# How has this been tested?

used `addpkg` locally to very/deep/foo.

Visited:
* http://127.0.0.1:8888/r/very/deep/foo
* http://127.0.0.1:8888/r/very/deep/foo/
* http://127.0.0.1:8888/r/very/deep/foo/foo.gno
* http://127.0.0.1:8888/r/very/deep/foo?help

All seemed to work fine.

### CODE REVIEW

**Comment by zivkovicmilos** [comment]
Hey @grepsuzette,

Thank you for the contribution 🙏 

Can you please update the PR description with examples that pass / fail for the modified regex?

**Comment by grepsuzette** [comment]
> Can you please update the PR description with examples that pass / fail for the modified regex?

OK I edited it! As mentionned in #564, before all those urls used to fail because the regex used didn't match, so it worked from CLI but not from the website.


OK wait, I have some problems with URLs like `http://127.0.0.1:8888/r/demo/users:anarcher`. Will check tomorrow!

**Comment by grepsuzette** [comment]
Ok it's fixed.

**Review by moul — APPROVED** [review]

**Comment by moul** [comment]
We should add basic unit tests on this; @grepsuzette could you add these tests?

**Comment by grepsuzette** [comment]
> We should add basic unit tests on this; @grepsuzette could you add these tests?
Should be done in https://github.com/gnolang/gno/pull/567

**Pull request closed without merging**
