### PR TITLE
chore: update CODEOWNERS

### PR DESCRIPTION
**Pull request by moul**
See title.

Depends on #1176 

<details><summary>Checklists...</summary>

## Contributors Checklist

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [x] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](../.benchmarks/README.md).

## Maintainers Checklist

- [ ] Checked that the author followed the guidelines in `CONTRIBUTING.md`
- [ ] Checked the conventional-commit (especially PR title and verb, presence of `BREAKING CHANGE:` in the body)
- [ ] Ensured that this PR is not a significant change or confirmed that the review/consideration process was appropriate for the change
</details>

### CODE REVIEW

**Comment by thehowl** [comment]
judging from the error, group needs write access to repo

**Comment by mvertes** [comment]
What is the purpose of the @gnolang/devrels ?

**Comment by moul** [comment]
The @gnolang/devrels team is all about making developers happy and eager to use our product.

Right now, we're focusing mainly on developers. We can split what we need to do into two groups: building stuff and everything else. 'Everything else' includes writing documentation, giving support, putting on presentations and events, and handling marketing. The core team, which you're a part of, handles the building part. Meanwhile, the devrel team takes care of the 'everything else,' either directly or indirectly.

**Comment by moul** [comment]
I suggest we consider a tool similar to this: [component-owners](https://github.com/dyladan/component-owners). However, its current version doesn't support "team" functionality. This tool was discussed [here](https://github.com/orgs/community/discussions/23042).

Given that it's based on YML, perhaps we can directly incorporate team support (with advanced YML features). This could streamline our management of contributors, reviewers, and related processes through commits.

**Review by ajnavarro — APPROVED** [review]

**Comment by moul** [comment]
I will soon revive this project, not just for devrels, but for the entire project and its subprojects.

Depends on #1176.

**Comment by moul** [comment]
Closing in favor of more recent changes.

**Pull request closed without merging**
