### PR TITLE
feat: Simple FSM package.

### PR DESCRIPTION
**Pull request by proggR**
# Description

Found myself wanting an FSM package for the WIP DAO-of-DAOs packages. So I made one.

## Contributors Checklist

- tests exist in `fsm_test`; creates Lightswitch and LoginManager (uses `Context`) machines and ensures they work as expected
- `AddTransition(State,State,Rule,*Context)` allows for new transitions to be added
- `RemoveTransition(State,State)` removes an existing transition
- `Transition(State)`  ensures requested state is a valid transition and updates `previousState` and `currentState`
- `Next()` returns a `Transitions` struct of the available transitions to allow for more dynamic state traversal logic by consumer
- `Current()` and `Previous()` return the corresponding `State`

### CODE REVIEW

**Review by thehowl — CHANGES_REQUESTED** [review]
Just some general feedback, don't know if this is WIP of not but I think it's early for a specific review

* Run `make fmt` please
* Document functions and general usage of the package; maybe a README?
* Variables should not be named like `name_` or in general have underscores unless you have a specific reason for it
* Likewise for constants (don't make them C-style `ALL_CAPS`; Go/Gno conventions are that variable should be `PascalCase` for exported and `camelCase` for unexported).

For a good introduction, see also:

* [Effective Go](https://go.dev/doc/effective_go)
* [Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments) on the Go Wiki

**Comment by thehowl** [comment]
Marking as draft for the time being; if you continue work on this feel free to mark as ready to review again.

**Comment by proggR** [comment]
Hey @thehowl, legit apologies for falling off this. I do think Gnoland needs a solid FSM package still because it pops up in so many other projects that it feels worth prioritizing as a basic library/package, and this was an attempt at a super basic one I'd love to see incorporated. Admittedly its been a while since I touched base and I fell off Gnoland grind stuff after not hearing back for a stretch, only to have that remind me... I started probing at Gnoland while chasing [my own thing](https://wethecommonwealth.org) I fell off for a bit while hacking in Gnoland (cuz its just too fun lol) so I got back onto the original grind :\ lol

I was participant to one of the dev chats and meant to follow along more after, but I'd love to setup a chat to see what things I either started or still have in a list as being relevant to Gnoland that would still be worth pursuing so I can get back to hacking out new constructs on it. I'm not sure my project will land on it, yet I do still find what its aiming for wildly interesting and would love to hurl random dev hours at just for the challenge of it and also just because... I love Go, making this project a default favourite tbh lol.

Apologies for pushing something with my generally Chainlink inspired/Solidity drawn styles. I did/should have known better, but was mostly just pushing progress at the time, so I'll happily reformat to get another code review phase if otherwise the FSM package is unobjectionable. Outside of naming conventions if you want to throw any other feedback in now I'll aim to incorporate it in the next push.

**Comment by thehowl** [comment]
Hi @proggR !

> Hey @thehowl, legit apologies for falling off this. I do think Gnoland needs a solid FSM package still because it pops up in so many other projects that it feels worth prioritizing as a basic library/package, and this was an attempt at a super basic one I'd love to see incorporated. Admittedly its been a while since I touched base and I fell off Gnoland grind stuff after not hearing back for a stretch, only to have that remind me... I started probing at Gnoland while chasing [my own thing](https://wethecommonwealth.org) I fell off for a bit while hacking in Gnoland (cuz its just too fun lol) so I got back onto the original grind :\ lol

Absolutely, no worries! We understand every external contributor has their own priorities and projects in life, so don't be sorry for falling off; we appreciate (and in the future, [reward](https://github.com/gnolang/gno/blob/master/docs/proof-of-contribution.md)) all contributions we get :)

> I was participant to one of the dev chats and meant to follow along more after, but I'd love to setup a chat to see what things I either started or still have in a list as being relevant to Gnoland that would still be worth pursuing so I can get back to hacking out new constructs on it. I'm not sure my project will land on it, yet I do still find what its aiming for wildly interesting and would love to hurl random dev hours at just for the challenge of it and also just because... I love Go, making this project a default favourite tbh lol.

I make an effort to check Discord from time to time, so feel free to reach out on #gnolang-dev or #gnolang-support to talk or bounce ideas.

> Apologies for pushing something with my generally Chainlink inspired/Solidity drawn styles. I did/should have known better, but was mostly just pushing progress at the time, so I'll happily reformat to get another code review phase if otherwise the FSM package is unobjectionable. Outside of naming conventions if you want to throw any other feedback in now I'll aim to incorporate it in the next push.

I'll admit I procrastinated doing a proper review mostly because 1. the underscores hurt my eyes 2. there are things beyond naming conventions I disagree with (eg. `IFSM` is not really useful, exporting `NewTransition` or `NewTransitions`, or `Transition` itself for that matter, is not really useful if `AddTransition` does not accept a `Transition`, ...). Which is why I suggested you to take a look around for Go coding/style-guides; but I suggest you also take a look at how some other packages are implemented (`p/demo/blog`, `p/demo/mux`...) for a good reference.

Consider the style and naming as a "first effort" we require of contributors; the code doesn't have to be perfect, but there should be an effort to make it pleasant to read and consistent with the rest of the repository, at least.

Thanks! :)

**Comment by thehowl** [comment]
Closing as draft for 1yr+. You're welcome to re-open to continue it.

**Pull request closed without merging**
