### PR TITLE
Add Mint to GRC721

### PR DESCRIPTION
**Pull request by giansalex**

### CODE REVIEW

**Comment by jaekwon** [comment]
Thank you for the contribution! I saw your tweet.

Is that a standard function in Ethereum anywhere? To keep it in line with ERC-721 I didn't include the Mint fuction.

In Go/Gno, the method doesn't have to be declared in an interface for it to be accessible by any caller. You could also do:

```go
type GRC721_Mint interface {
	Mint(to std.Address, data string) TokenID
}

var x = nft.GetGRC721().(GRC721_Mint)
x.Mint(...)
```

**Comment by giansalex** [comment]
Thanks, is what i needed.

**Comment by giansalex** [comment]
I saw that `Mint` func was only in `grc721` but this is private, or is it different here?

**Comment by jaekwon** [comment]
Can you share how you got that error? The zrealm_nft4.go testfile shows it working well directly. Maybe there's some other bug.

**Comment by giansalex** [comment]
this is the [initial contract](https://gno.land/r/fancy/contract.go), when `Mint` function is called, i got that error.

**Pull request closed without merging**
