### PR TITLE
fix: re-create blocks on for loop iterations

### LINKED ISSUE #1135: for loops maintain the same block on iteration, which is referenced in any closures generated within
title might be confusing, but here's the example:

```go
package main

func main() {
        var fns []func()
        for _, v := range []int{1, 2, 3} {
                x := v*100 + v
                fns = append(fns, func() { println(x) })
        }
        for _, fn := range fns {
                fn()
        }
}
```

(the `x :=` declaration is used to demonstrate that this does not reference `v`, whereby the behaviour talked about here would [actually be correct in the current go specification](https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable), though [this is due to change in go1.22](https://github.com/golang/go/issues/60078))

go behaviour (expected):

```
101
202
303
```

gno behaviour:

```
303
303
303
```

### PR DESCRIPTION
**Pull request by thehowl**
This is an attempt at an alternative to fix #1135. See a current solution at #1585.

The solution is simple: for all our for loops, whenever we reach the end of its body and are about to go back at the top, re-create their Blocks from scratch, copying over the `bodyStmt`. In the case of three-clause for loops, copy over any current values of the declared initialization variables. This is consistent with the behaviour [as of Go 1.22](https://go.dev/ref/spec#For_statements).

This fix is "dumb", for now. I'm pretty sure re-creating a Block on each iteration is not the best thing for performance, and this may be a step that we can try to "optimize out" if the for loop doesn't generate a closure (as most for loops are). However, it is a very small patch, and I'd like to gauge whether we like this fix and should adopt some variation of it or not.

Credit to maxwell for the tests added. (Note: the `goto` tests still don't work; however, I think the fix for the `goto` tests involves correctly "understanding" the difference between assignment/defintiion within the GnoVM, and as such are out of scope here. Naturally, if there is an alternative fix that gets within the same patch to fix this issue and the goto issue, I'm all ears)

cc/ @jaekwon @deelawn @ltzmaxwell

### CODE REVIEW

**Comment by thehowl** [comment]
Closing for house-keeping and seeing as you made another PR

**Comment by jaekwon** [comment]
My PR isn't good, but found a better way which we talked about in the call.
Basically, ForStmt bodies should be wrapped with a BlockStmt and i := i if necessary,
and
GOTO:
{
   should
   look
   like
   this
}
GOTO2:
{
   if
   implicit
   loop
}

**Comment by ltzmaxwell** [comment]
loop var escape issues is being fixed in #2429 and #2440 , we can put a hold on reviewing this PR and decide our next steps based on the status of the #2429 and #2440 solution.

**Comment by thehowl** [comment]
Closing in favour of other PRs.

**Pull request closed without merging**
