### PR TITLE
feat(cmd/gno)!: change all `-verbose` flags to `-v`

### PR DESCRIPTION
**Pull request by thehowl**
Per the decision on #1555, we now have some exceptions for common scenarios where short flags make sense. `gno test -v` is super-useful as it connects to the muscle memory a Go developer has (with `go test -v`), so this PR adds it.

### CODE REVIEW

**Review by harry-hov — APPROVED** [review]
can you do this for other commands as well? (wherever it makes sense)

**Comment by harry-hov** [comment]
what do you think about removing `-verbose` and just keep `-v`?

**Comment by thehowl** [comment]
@harry-hov bold, I like it :) done

**Review by leohhhn — APPROVED** [review]
You've just shortened the testing time locally 😎

**Comment by thehowl** [comment]
After posting this on signal, there seems to be an overwhelming consensus to do this, so going ahead and merging :)

**Pull request merged**
