### PR TITLE
feat(go): bump go 1.20 to 1.21

### PR DESCRIPTION
**Pull request by gfanton**
As Go `1.22` has been released, we can update our version from `1.20` to `1.21`. 
In the process, I've also updated the `slog` import to use the one from the standard library.

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Review by moul — APPROVED** [review]

**Comment by moul** [comment]
If there are any features from go1.21 that should be implemented, please feel free to suggest them in an issue.

**Comment by thehowl** [comment]
can you (have you) also updated any uses of x/exp/slices?

**Comment by gfanton** [comment]
> can you (have you) also updated any uses of x/exp/slices?

good catch, I will update this one too and check for all other `x` libs

**Review by albttx — APPROVED** [review]

**Review by zivkovicmilos — APPROVED** [review]
Looks great 💯 

Thank you for bumping the loggers as well, it was a pain with `1.20` 🙏

**Review by thehowl — APPROVED** [review]
changed the version [in a few more places you missed](https://github.com/gnolang/gno/pull/1654/commits/2f02ed702e25b2ced5e2c0354296ca1f2bb07968). should be all good, merging after CI :)

**Pull request merged**
