### PR TITLE
feat: add Sine + Cosine + Signbit

### PR DESCRIPTION
**Pull request by schollz**
# Description

This PR adds in the `math.Sin` and `math.Cos` methods. This file is from the Pre-Go 1 history: https://github.com/golang/go/blob/e4de2e7fd04c92d4035cd268d5043f2380aef437/src/pkg/math/sin.go The future versions had trouble with the gno language due to unsupported features.

# How has this been tested?

Yes, I am using it in a realm that I am working on (https://github.com/schollz/gno/tree/bytebeat). There are no tests for the math packages, but I can add tests if needed.

### CODE REVIEW

**Comment by schollz** [comment]
@albttx Yes, it never hurts! I can add some tests.

**Comment by schollz** [comment]
Tests added for `Signbit`, `Sin`, `Cos`. @moul - shall I continue to add all the tests for the current `math` Gno packages?

**Review by zivkovicmilos — APPROVED** [review]
Looks good 💯 

Thank you for the addition 🙏

**Review by albttx — APPROVED** [review]

**Review by ajnavarro — APPROVED** [review]

**Comment by moul** [comment]
Can you update this file: https://github.com/gnolang/gno/blob/master/gnovm/docs/go-gno-compatibility.md#stdlibs?

**Comment by schollz** [comment]
> Can you update this file: https://github.com/gnolang/gno/blob/master/gnovm/docs/go-gno-compatibility.md#stdlibs?

Yes! Added now.

**Comment by jaekwon** [comment]
reading now

**Comment by ajnavarro** [comment]
pinging @moul with the final vote to merge this.

**Review by moul — APPROVED** [review]

**Pull request merged**
