### PR TITLE
fix(docs): JSX error

### PR DESCRIPTION
**Pull request by albttx**
https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#bad-usage-of--1

Tested locally and it's work fine.

### CODE REVIEW

**Review by moul — CHANGES_REQUESTED** [review]
Ideal option: Let's address the specific Markdown needs in the `docs.gno.land` repository with a script.

Acceptable option: We can merge this PR, but only if you add a linter that fails when this formatting is not applied.

**Comment by leohhhn** [comment]
@moul 

For this case specifically, the "tag" was used as a long-help in the gnodev CLI. It seems docusaurus didn't like that

**Comment by moul** [comment]
We should add a linter to this repository, as suggested in my second option.
Then, we should either manually add the backslashes or have our automatic documentation generation scripts handle that task automatically.

I'm comfortable keeping the `<>` in the CLI output, as that appears to be a common standard for mandatory parameters that I'm accustomed to. However, I'm open to removing them if more people believe we should.

**Comment by leohhhn** [comment]
I can add the `<>` lint to the linter after #2125. Let's merge this now

**Review by leohhhn — APPROVED** [review]

**Comment by moul** [comment]
The problem is that issue #2125 will likely never be merged. Can you implement your linter now?

**Comment by leohhhn** [comment]
Superseded by #2394 & other linter PRs.

**Pull request closed without merging**
