### PR TITLE
chore: attempt to improve OriginCall funcs

### LINKED ISSUE #481: test: unable to use `std.AssertOriginCall` in `_test` files
In test context, `std.AssertOriginCall` is overrided by the following code : 

```go
			func(m *gno.Machine) {
				isOrigin := len(m.Frames) == 3
				if !isOrigin {
					panic("invalid non-origin call")
				}
			}
```

Which works well for `_filetest` files, but not for `_test` files because the number of `m.Frames` is not 3.

I would like to make it compatible for both scenario, but for that I need to understand why checking the number of frames asserts that the caller is actually the signer of the tx. Any hint would be appreciated.

---

The frames for `_filetest` (dumped by `spew.Dump()`) : 
```
([]gnolang.Frame) (len=3 cap=4) {
 (gnolang.Frame) [FRAME FUNC:main RECV:(undefined) (0 args) 2/0/0/0/1 LASTPKG:main LASTRLM:Realm(nil)],
 (gnolang.Frame) [FRAME FUNC:CreateContrib RECV:(undefined) (2 args) 5/1/0/2/2 LASTPKG:main LASTRLM:Realm(nil)],
 (gnolang.Frame) [FRAME FUNC:AssertOriginCall RECV:(undefined) (0 args) 7/2/0/3/3 LASTPKG:gno.land/r/gnoland/dao/eval LASTRLM:Realm{Path:"gno.land/r/gnoland/dao/eval",Time:4}#EA8DA22C5FB56500FCF01D8C35C2F076DFA9771B]
}
```

The frames for `_test` : 
```
([]gnolang.Frame) (len=7 cap=8) {
 (gnolang.Frame) [FRAME FUNC:runtest RECV:(undefined) (1 args) 1/0/0/0/1 LASTPKG:./examples/gno.land/r/gnoland/dao/eval LASTRLM:Realm(nil)],
 (gnolang.Frame) [FRAME LABEL:  2/1/0/1/2],
 (gnolang.Frame) [FRAME FUNC:RunTest RECV:(undefined) (3 args) 6/2/0/3/4 LASTPKG:./examples/gno.land/r/gnoland/dao/eval LASTRLM:Realm(nil)],
 (gnolang.Frame) [FRAME FUNC:tRunner RECV:(undefined) (3 args) 8/3/0/4/5 LASTPKG:testing LASTRLM:Realm(nil)],
 (gnolang.Frame) [FRAME FUNC:TestCreateContrib RECV:(undefined) (1 args) 11/4/0/6/6 LASTPKG:testing LASTRLM:Realm(nil)],
 (gnolang.Frame) [FRAME FUNC:CreateContrib RECV:(undefined) (2 args) 14/5/0/8/7 LASTPKG:./examples/gno.land/r/gnoland/dao/eval LASTRLM:Realm(nil)],
 (gnolang.Frame) [FRAME FUNC:AssertOriginCall RECV:(undefined) (0 args) 16/6/0/9/8 LASTPKG:./examples/gno.land/r/gnoland/dao/eval LASTRLM:Realm(nil)]
}
```

### PR DESCRIPTION
**Pull request by tbruyelle**
`AssertOriginCall` and `IsOriginCall` relies on the number of frames to determine if the function was called by a gno transaction (definition taken from `examples/gno.land/r/demo/banktest/README.md`). Since this number is different in the context of test and filetest, the 2 functions are overrided during test setup, but the override works only for filetest files and not for test files.

This change allows `AssertOriginCall` and `IsOriginCall` to rely on message's signers instead of frames. If the message has at least one signer, we consider the function was called by a gno tx. As a result, the functions no longer needs to be overrided in test setup, and they work both for filetest files and test files.

Fix #481

### CODE REVIEW

**Comment by moul** [comment]
Hey @tbruyelle, sorry for the delay; everything looks good, however, to make sure that it's stable and stays stable over time.

It would be nice to add tests checking the consistency of this approach in the three main conditions:
* simulating a TX,
* testing with `_test.gno`,
* testing with `_filetest.gno`.

We may add a unit test suite simulating the various Machine contexts so we can add more and more tests for `std` over time.
It may be done in another PR and by someone else, but I was wondering what do you think.

**Comment by tbruyelle** [comment]
Hey @moul no problem for the delay. You're right some tests are missing for a `_test.gno` file (which was the root problem addressed by this change actually!).

For `_filetest.gno` files, only `AssertOriginCall` is actually tested (for instance in `demo/banktest`), but not `IsOriginCall`, I will add a case for that.

About simulating a TX, could you give more details? Is it some kind of integration test ?

**Comment by tbruyelle** [comment]
I added some tests for `AssertOriginCall` and `IsOriginCall` here dde938d, but that required some changes in the body of `AssertOriginCall`.

Indeed, the panic in this function occurred in go code, so it wasn't recoverable by gno code. Switching from `panic` to `machine.Panic` fixed that. Not sure if this switch has other consequences, I can just assert that in both scenario, the program is stopped.

Secondly, I reverted the `context.Msg = testutils.NewTestMsg(caller)` (introduced in this PR), because else, `AssertOriginCall` is always true because there's always a signer. Now the message is set only if `std.TestSetOrigCaller()` or `std.TestSetOrigPkgAddr()` are invoked. Because of that I had to fix a bunch of other tests in the `examples` folder.

Lastly, I looked at `GetCallerAt` which still uses the number of frames to determine what will be returned. And now I'm beginning to doubt the validity of my change. I think we need to understand what is the relations with the number of frames and the callers.

**Comment by moul** [comment]
Please share your thoughts on PR #683.

**Comment by tbruyelle** [comment]
Closed in favor of #703

**Pull request closed without merging**
